// Code generated by injector. DO NOT EDIT.

package handler

import (
	config "github.com/mickamy/sampay/config"
	di "github.com/mickamy/sampay/internal/di"
	usecase "github.com/mickamy/sampay/internal/domain/auth/usecase"
	oauth "github.com/mickamy/sampay/internal/lib/oauth"
)

// NewOAuth initializes dependencies and constructs OAuth.
func NewOAuth(infra *di.Infra) *OAuth {
	oAuth := config.OAuth()
	resolverFromConfig := oauth.NewResolverFromConfig(oAuth)
	getOAuthURL := usecase.NewGetOAuthURL(resolverFromConfig)
	oAuthCallback := usecase.NewOAuthCallback(infra, resolverFromConfig)

	return &OAuth{
		getOAuthURL:   getOAuthURL,
		oauthCallback: oAuthCallback,
	}
}

// MustNewOAuth initializes dependencies and constructs OAuth or panics on failure.
func MustNewOAuth(infra *di.Infra) *OAuth {
	oAuth := config.OAuth()
	resolverFromConfig := oauth.NewResolverFromConfig(oAuth)
	getOAuthURL := usecase.NewGetOAuthURL(resolverFromConfig)
	oAuthCallback := usecase.NewOAuthCallback(infra, resolverFromConfig)

	return &OAuth{
		getOAuthURL:   getOAuthURL,
		oauthCallback: oAuthCallback,
	}
}

// NewSession initializes dependencies and constructs Session.
func NewSession(infra *di.Infra) *Session {
	refreshToken := usecase.NewRefreshToken(infra)
	logout := usecase.NewLogout(infra)

	return &Session{
		refreshToken: refreshToken,
		logout:       logout,
	}
}

// MustNewSession initializes dependencies and constructs Session or panics on failure.
func MustNewSession(infra *di.Infra) *Session {
	refreshToken := usecase.NewRefreshToken(infra)
	logout := usecase.NewLogout(infra)

	return &Session{
		refreshToken: refreshToken,
		logout:       logout,
	}
}
