all:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"
    ansible_ssh_port: "{{ lookup('env', 'ANSIBLE_SSH_PORT') }}"
    ansible_python_interpreter: /usr/bin/python3
    certbot_email: "{{ lookup('env', 'CERTBOT_EMAIL') }}"
  children:
    stg:
      vars:
        env: staging
        domain_name: stg.sampay.link
      hosts:
        stg.sampay.link:
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    prod:
      vars:
        env: production
        domain_name: sampay.link
      hosts:
        sampay.link:
