all:
  vars:
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3
    ansible_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"
    ansible_port: "{{ lookup('env', 'ANSIBLE_SSH_PORT') }}"
    certbot_email: "{{ lookup('env', 'CERTBOT_EMAIL') }}"
    base_domain_name: sampay.link
  children:
    stg:
      vars:
        env: staging
        domain_name: "stg.{{ base_domain_name }}"
      hosts:
        stg.sampay.link:
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    prod:
      vars:
        env: production
        domain_name: "{{ base_domain_name }}"
      hosts:
        sampay.link:
