// Code generated by injector. DO NOT EDIT.

package di

import (
	context "context"
	config "github.com/mickamy/sampay/config"
)

// NewInfra initializes dependencies and constructs Infra.
func NewInfra(context context.Context) (*Infra, error) {
	common := config.Common()
	database := config.Database()
	provideDB, err := ProvideDB(context, common, database)
	if err != nil {
		return nil, err
	}
	provideWriterDB, err := ProvideWriterDB(context, common, database)
	if err != nil {
		return nil, err
	}
	provideReaderDB, err := ProvideReaderDB(context, common, database)
	if err != nil {
		return nil, err
	}
	kVS := config.KVS()
	provideKVS, err := ProvideKVS(kVS)
	if err != nil {
		return nil, err
	}
	provideS3, err := ProvideS3(context)
	if err != nil {
		return nil, err
	}

	return &Infra{
		DB:       provideDB,
		WriterDB: provideWriterDB,
		ReaderDB: provideReaderDB,
		KVS:      provideKVS,
		S3:       provideS3,
	}, nil
}

// MustNewInfra initializes dependencies and constructs Infra or panics on failure.
func MustNewInfra(context context.Context) *Infra {
	common := config.Common()
	database := config.Database()
	provideDB, err := ProvideDB(context, common, database)
	if err != nil {
		panic(err)
	}
	provideWriterDB, err := ProvideWriterDB(context, common, database)
	if err != nil {
		panic(err)
	}
	provideReaderDB, err := ProvideReaderDB(context, common, database)
	if err != nil {
		panic(err)
	}
	kVS := config.KVS()
	provideKVS, err := ProvideKVS(kVS)
	if err != nil {
		panic(err)
	}
	provideS3, err := ProvideS3(context)
	if err != nil {
		panic(err)
	}

	return &Infra{
		DB:       provideDB,
		WriterDB: provideWriterDB,
		ReaderDB: provideReaderDB,
		KVS:      provideKVS,
		S3:       provideS3,
	}
}
