// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/redis/go-redis/v9"
	"mickamy.com/sampay/config"
	"mickamy.com/sampay/internal/cli/infra/storage/database"
	"mickamy.com/sampay/internal/domain/auth/di"
	"mickamy.com/sampay/internal/domain/auth/handler"
	"mickamy.com/sampay/internal/domain/auth/repository"
	"mickamy.com/sampay/internal/domain/auth/usecase"
	di2 "mickamy.com/sampay/internal/domain/registration/di"
	handler2 "mickamy.com/sampay/internal/domain/registration/handler"
	usecase2 "mickamy.com/sampay/internal/domain/registration/usecase"
	di3 "mickamy.com/sampay/internal/domain/user/di"
	repository2 "mickamy.com/sampay/internal/domain/user/repository"
)

// Injectors from wire.go:

func InitInfras() (Infras, error) {
	databaseConfig := config.Database()
	db, err := provideDB(databaseConfig)
	if err != nil {
		return Infras{}, err
	}
	readWriter, err := provideReadWriter(databaseConfig)
	if err != nil {
		return Infras{}, err
	}
	writer, err := provideWriter(databaseConfig)
	if err != nil {
		return Infras{}, err
	}
	reader, err := provideReader(databaseConfig)
	if err != nil {
		return Infras{}, err
	}
	kvsConfig := config.KVS()
	client, err := provideKVS(kvsConfig)
	if err != nil {
		return Infras{}, err
	}
	diInfras := Infras{
		DB:         db,
		ReadWriter: readWriter,
		Writer:     writer,
		Reader:     reader,
		KVS:        client,
	}
	return diInfras, nil
}

func InitAuthRepositories(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di.Repositories {
	authentication := repository.NewAuthentication(db)
	session := repository.NewSession(kvs)
	repositories := di.Repositories{
		Authentication: authentication,
		Session:        session,
	}
	return repositories
}

func InitAuthUseCases(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di.UseCases {
	session := repository.NewSession(kvs)
	user := repository2.NewUser(db)
	authenticateUser := usecase.NewAuthenticateUser(reader, session, user)
	authentication := repository.NewAuthentication(db)
	createSession := usecase.NewCreateSession(reader, authentication, session, user)
	refreshSession := usecase.NewRefreshSession(session)
	deleteSession := usecase.NewDeleteSession(session)
	useCases := di.UseCases{
		AuthenticateUser: authenticateUser,
		CreateSession:    createSession,
		RefreshSession:   refreshSession,
		DeleteSession:    deleteSession,
	}
	return useCases
}

func InitAuthHandlers(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di.Handlers {
	authentication := repository.NewAuthentication(db)
	session := repository.NewSession(kvs)
	user := repository2.NewUser(db)
	createSession := usecase.NewCreateSession(reader, authentication, session, user)
	refreshSession := usecase.NewRefreshSession(session)
	handlerSession := handler.NewSession(createSession, refreshSession)
	handlers := di.Handlers{
		Session: handlerSession,
	}
	return handlers
}

func InitRegistrationUseCases(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di2.UseCases {
	authentication := repository.NewAuthentication(db)
	session := repository.NewSession(kvs)
	user := repository2.NewUser(db)
	createAccount := usecase2.NewCreateAccount(writer, authentication, session, user)
	useCases := di2.UseCases{
		CreateAccount: createAccount,
	}
	return useCases
}

func InitRegistrationHandlers(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di2.Handlers {
	authentication := repository.NewAuthentication(db)
	session := repository.NewSession(kvs)
	user := repository2.NewUser(db)
	createAccount := usecase2.NewCreateAccount(writer, authentication, session, user)
	account := handler2.NewAccount(createAccount)
	handlers := di2.Handlers{
		Account: account,
	}
	return handlers
}

func InitUserRepositories(db *database.DB, readWriter *database.ReadWriter, writer *database.Writer, reader *database.Reader, kvs *redis.Client) di3.Repositories {
	user := repository2.NewUser(db)
	repositories := di3.Repositories{
		User: user,
	}
	return repositories
}

// wire.go:

func InitConfigs() Configs {
	return NewConfigs()
}
