- name: Configure Sampay backend server
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create API systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-api.service
        content: |
          [Unit]
          Description=Sampay API Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/backend
          ExecStart=/home/ec2-user/sampay/backend/build/api
          Restart=always
          Environment="AWS_REGION={{ aws_region }}"
          Environment="ENV={{ env }}"
          Environment="PACKAGE_ROOT=/home/ec2-user/sampay/backend"
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay/api.log
          StandardError=append:/var/log/redis/api.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Create worker systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-worker.service
        content: |
          [Unit]
          Description=Sampay worker Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/backend
          ExecStart=/home/ec2-user/sampay/backend/build/worker
          Restart=always
          Environment="AWS_REGION={{ aws_region }}"
          Environment="ENV={{ env }}"
          Environment="PACKAGE_ROOT=/home/ec2-user/sampay/backend"
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay/worker.log
          StandardError=append:/var/log/redis/worker.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable API service
      ansible.builtin.systemd:
        name: sampay-api
        enabled: true

    - name: Enable worker service
      ansible.builtin.systemd:
        name: sampay-worker
        enabled: true

    - name: Set ENV to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "ENV={{ env }}"
        create: true
        state: present
        mode: '0644'

    - name: Set AWS_REGION to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "AWS_REGION={{ aws_region }}"
        create: true
        state: present
        mode: '0644'
