- name: Configure Sampay backend server
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create frontend backend environment file
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-backend.env
        content: |
          AWS_REGION={{ aws_region }}
          ENV={{ env }}
          export AWS_REGION
          export ENV
        owner: root
        group: root
        mode: '0644'

    - name: Create API blue systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-api-blue.service
        content: |
          [Unit]
          Description=Sampay API blue Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/backend-blue
          ExecStart=/home/ec2-user/sampay/backend-blue/build/api
          Restart=always
          EnvironmentFile=/etc/systemd/system/sampay-backend.env
          Environment="PACKAGE_ROOT=/home/ec2-user/sampay/backend-blue"
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay-blue/api.log
          StandardError=append:/var/log/sampay-blue/api.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Create API green systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-api-green.service
        content: |
          [Unit]
          Description=Sampay API green Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/backend-green
          ExecStart=/home/ec2-user/sampay/backend-green/build/api
          Restart=always
          EnvironmentFile=/etc/systemd/system/sampay-backend.env
          Environment="PACKAGE_ROOT=/home/ec2-user/sampay/backend-green"
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay-green/api.log
          StandardError=append:/var/log/sampay-green/api.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Create worker systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-worker.service
        content: |
          [Unit]
          Description=Sampay worker Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/backend
          ExecStart=/home/ec2-user/sampay/backend/build/worker
          Restart=always
          Environment="AWS_REGION={{ aws_region }}"
          Environment="ENV={{ env }}"
          Environment="PACKAGE_ROOT=/home/ec2-user/sampay/backend"
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay/worker.log
          StandardError=append:/var/log/sampay/worker.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start api blue service
      ansible.builtin.systemd:
        name: sampay-api-blue
        enabled: true

    - name: Enable api green service
      ansible.builtin.systemd:
        name: sampay-api-green
        enabled: true

    - name: Enable worker service
      ansible.builtin.systemd:
        name: sampay-worker
        enabled: true

    - name: Set ENV to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "ENV={{ env }}"
        create: true
        state: present
        mode: '0644'

    - name: Set AWS_REGION to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "AWS_REGION={{ aws_region }}"
        create: true
        state: present
        mode: '0644'

    - name: Set PACKAGE_ROOT to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "PACKAGE_ROOT=/home/ec2-user/sampay/backend"
        create: true
        state: present
        mode: '0644'

    - name: Create directory
      ansible.builtin.file:
        path: /home/ec2-user/sampay
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
