- name: Configure Sampay frontend server
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create frontend systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-frontend.service
        content: |
          [Unit]
          Description=Sampay frontend Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/frontend
          ExecStartPre=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/node \
            /home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/npm ci
          ExecStartPre=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/node \
            /home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/npm run build
          ExecStart=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/node \
            /home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/npm run start
          EnvironmentFile=/etc/systemd/system/sampay-frontend.env
          Environment="ENVIRONMENT={{ env }}"
          Restart=always
          User=ec2-user
          Group=ec2-user

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Create frontend systemd environment file
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-frontend.env
        content: |
          PATH=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin:/usr/local/bin:/usr/bin:/bin
          NODE_PATH=/home/ec2-user/.nvm/versions/node{{ node_version }}/lib/node_modules
          NVM_DIR=/home/ec2-user/.nvm
          API_BASE_URL=http:localhost:8080
          export PATH
          export NODE_PATH
          export NVM_DIR
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start frontend service
      ansible.builtin.systemd:
        name: sampay-frontend
        enabled: true
