- name: Configure Sampay frontend server
  hosts: all
  gather_facts: false
  become: true
  vars:
    basic_user: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    basic_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

  tasks:
    - name: Create frontend systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-frontend.service
        content: |
          [Unit]
          Description=Sampay frontend Service
          After=network.target

          [Service]
          WorkingDirectory=/home/ec2-user/sampay/frontend
          ExecStart=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/node \
            /home/ec2-user/.nvm/versions/node/{{ node_version }}/bin/npm run start
          EnvironmentFile=/etc/systemd/system/sampay-frontend.env
          Environment="ENVIRONMENT={{ env }}"
          Restart=always
          User=ec2-user
          Group=ec2-user

          StandardOutput=append:/var/log/sampay/frontend.log
          StandardError=append:/var/log/sampay/frontend.log

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Create frontend systemd environment file
      ansible.builtin.copy:
        dest: /etc/systemd/system/sampay-frontend.env
        content: |
          PATH=/home/ec2-user/.nvm/versions/node/{{ node_version }}/bin:/usr/local/bin:/usr/bin:/bin
          NODE_PATH=/home/ec2-user/.nvm/versions/node{{ node_version }}/lib/node_modules
          NVM_DIR=/home/ec2-user/.nvm
          API_BASE_URL=http://localhost:8080/api
          export PATH
          export NODE_PATH
          export NVM_DIR
          {% if basic_user is defined and basic_user | length > 0 %}
          BASIC_USER={{ basic_user }}
          export BASIC_USER
          {% endif %}
          {% if basic_password is defined and basic_password | length > 0 %}
          BASIC_PASSWORD={{ basic_password }}
          export BASIC_PASSWORD
          {% endif %}
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start frontend service
      ansible.builtin.systemd:
        name: sampay-frontend
        enabled: true

    - name: Create directory
      ansible.builtin.file:
        path: /home/ec2-user/sampay
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
