- name: Configure logs for Sampay services
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure /var/log/sampay exists
      ansible.builtin.file:
        path: /var/log/sampay
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
