---
- name: Install PostgreSQL 16 on AWS Linux 2023
  hosts: all
  become: true
  tasks:
    - name: Ensure necessary packages are installed
      ansible.builtin.dnf:
        name:
          - postgresql16-server
          - postgresql16
        state: present

    - name: Install PostgreSQL 16 server
      ansible.builtin.dnf:
        name: postgresql16-server
        state: present

    - name: Initialize PostgreSQL database
      ansible.builtin.command:
        cmd: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Configure PostgreSQL to use scram-sha-256
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        line: "password_encryption = 'scram-sha-256'"
        regexp: "^password_encryption"
        state: present

    - name: Allow localhost-only connections
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host all all 127.0.0.1/32 scram-sha-256"
        regexp: "^host all all .* scram-sha-256"
        state: present

    - name: Allow IPv6 localhost connections
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host all all ::1/128 scram-sha-256"
        regexp: "^host all all .* scram-sha-256"
        state: present

    - name: Start and enable PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
        enabled: true
