- name: Install Redis on Amazon Linux 2023
  hosts: all
  become: true
  tasks:
    - name: Install required dependencies
      ansible.builtin.dnf:
        name:
          - gcc
          - make
          - tar
          - wget
        state: present

    - name: Download Redis source code
      ansible.builtin.get_url:
        url: https://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
        dest: /tmp/redis-{{ redis_version }}.tar.gz
        mode: '0644'

    - name: Set permissions for Redis source
      ansible.builtin.file:
        path: /tmp/redis-{{ redis_version }}.tar.gz
        mode: '0755'

    - name: Unzip Redis source
      ansible.builtin.unarchive:
        src: /tmp/redis-{{ redis_version }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: Build Redis
      community.general.make:
        chdir: /tmp/redis-{{ redis_version }}

    - name: Install Redis
      community.general.make:
        chdir: /tmp/redis-{{ redis_version }}
        target: install

    - name: Copy Redis configuration file
      ansible.builtin.command:
        cmd: cp /tmp/redis-{{ redis_version }}/redis.conf /etc/redis.conf
      args:
        creates: /etc/redis.conf

    - name: Set ownership and permissions for Redis configuration
      ansible.builtin.file:
        path: /etc/redis.conf
        owner: root
        group: root
        mode: '0644'

    - name: Remove Redis archive
      ansible.builtin.file:
        path: /tmp/redis-{{ redis_version }}.tar.gz
        state: absent

    - name: Remove Redis source directory
      ansible.builtin.file:
        path: /tmp/redis-{{ redis_version }}
        state: absent

    - name: Create Redis group
      ansible.builtin.group:
        name: redis
        system: true

    - name: Create Redis user
      ansible.builtin.user:
        name: redis
        group: redis
        system: true
        create_home: false

    - name: Create redis data directory
      ansible.builtin.file:
        path: /var/lib/redis
        state: directory
        owner: redis
        group: redis
        mode: '0750'

    - name: Create Redis systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/redis.service
        content: |
          [Unit]
          Description=Redis In-Memory Data Store
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/redis-server /etc/redis.conf
          ExecStop=/usr/local/bin/redis-cli shutdown
          Restart=always
          User=redis
          Group=redis

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Redis service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: true

    - name: Verify Redis is running
      ansible.builtin.command:
        cmd: redis-cli ping
      register: redis_status
      changed_when: false
      ignore_errors: true

    - name: Print Redis status
      ansible.builtin.debug:
        msg: "Redis status: {{ redis_status.stdout }}"
