services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        MAIN_GO_FILE: /src/cmd/api/main.go
        BIN_NAME: api
      secrets:
        - buf_token
    env_file:
      - .env.docker
    volumes:
      - ./backend:/src:delegated
      - /src/build
      - go:/go
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
      secrets:
        - buf_token
    volumes:
      - ./frontend:/usr/src:delegated
      - /usr/src/build
      - node_modules:/usr/src/node_modules
    ports:
      - "5173:5173"

  postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGUSER: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      DB_NAME: sampay
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

secrets:
  buf_token:
    file: secrets/buf_token

volumes:
  go:
  node_modules:
  postgres:
