// Code generated by automapper. DO NOT EDIT.

package mapper

import (
	eventv1 "github.com/mickamy/sampay/gen/event/v1"
	"github.com/mickamy/sampay/internal/domain/event/model"
	"github.com/mickamy/sampay/internal/lib/converter"
)

// ToV1EventParticipantPtr converts *EventParticipant to *EventParticipant.
func ToV1EventParticipantPtr(src *model.EventParticipant) *eventv1.EventParticipant {
	if src == nil {
		return nil
	}

	return &eventv1.EventParticipant{
		Id:        src.ID,
		EventId:   src.EventID,
		Name:      src.Name,
		Tier:      converter.IntToInt32(src.Tier),
		Status:    converter.ToV1ParticipantStatus(src.Status),
		Amount:    converter.IntToInt32(src.Amount),
		CreatedAt: converter.TimeToTimestamppb(src.CreatedAt),
	}

}

// ToV1EventParticipant converts EventParticipant to EventParticipant.
func ToV1EventParticipant(src model.EventParticipant) eventv1.EventParticipant {

	return eventv1.EventParticipant{
		Id:        src.ID,
		EventId:   src.EventID,
		Name:      src.Name,
		Tier:      converter.IntToInt32(src.Tier),
		Status:    converter.ToV1ParticipantStatus(src.Status),
		Amount:    converter.IntToInt32(src.Amount),
		CreatedAt: converter.TimeToTimestamppb(src.CreatedAt),
	}

}
