// Code generated by automapper. DO NOT EDIT.

package mapper

import (
	eventv1 "github.com/mickamy/sampay/gen/event/v1"
	"github.com/mickamy/sampay/internal/domain/event/model"
	"github.com/mickamy/sampay/internal/lib/converter"
)

// ToV1EventPtr converts *Event to *Event.
func ToV1EventPtr(src *model.Event) *eventv1.Event {
	if src == nil {
		return nil
	}

	return &eventv1.Event{
		Id:          src.ID,
		UserId:      src.UserID,
		Title:       src.Title,
		Description: src.Description,
		TotalAmount: converter.IntToInt32(src.TotalAmount),
		TierCount:   converter.IntToInt32(src.TierCount),
		HeldAt:      converter.TimeToTimestamppb(src.HeldAt),
	}

}

// ToV1Event converts Event to Event.
func ToV1Event(src model.Event) eventv1.Event {

	return eventv1.Event{
		Id:          src.ID,
		UserId:      src.UserID,
		Title:       src.Title,
		Description: src.Description,
		TotalAmount: converter.IntToInt32(src.TotalAmount),
		TierCount:   converter.IntToInt32(src.TierCount),
		HeldAt:      converter.TimeToTimestamppb(src.HeldAt),
	}

}
