ARG GO_VERSION=1.23.4

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}

ARG MAIN_GO_FILE
ENV MAIN_GO_FILE=$MAIN_GO_FILE
ARG BIN_NAME
ENV BIN_NAME=$BIN_NAME

WORKDIR /src

ADD Makefile ./
RUN make install-build install-dev

RUN --mount=type=secret,id=buf_token \
    BUF_TOKEN=$(cat /run/secrets/buf_token) && \
    echo "$BUF_TOKEN" | buf registry login buf.build --token-stdin

ADD . .

ADD go.mod go.sum ./
RUN go mod download -x

CMD ["air", "--build.cmd", "go build -o ./build/$BIN_NAME $MAIN_GO_FILE", "--build.bin", "./build/$BIN_NAME"]
