ARG GO_VERSION=1.26.0

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}

ARG MAIN_GO_FILE
ENV MAIN_GO_FILE=$MAIN_GO_FILE
ARG BIN_NAME
ENV BIN_NAME=$BIN_NAME

WORKDIR /src

COPY . .

RUN go mod download

CMD ["sh", "-c", "go tool air -c .air.${BIN_NAME}.toml"]
