// Code generated by automapper. DO NOT EDIT.

package mapper

import (
	userv1 "github.com/mickamy/sampay/gen/user/v1"
	"github.com/mickamy/sampay/internal/domain/user/model"
)

// ToV1UserPtr converts *EndUser to *User.
func ToV1UserPtr(src *model.EndUser) *userv1.User {
	if src == nil {
		return nil
	}

	return &userv1.User{
		Id:   src.UserID,
		Slug: src.Slug,
	}

}

// ToV1User converts EndUser to User.
func ToV1User(src model.EndUser) userv1.User {

	return userv1.User{
		Id:   src.UserID,
		Slug: src.Slug,
	}

}
