// Code generated by automapper. DO NOT EDIT.

package mapper

import (
	"fmt"

	userv1 "github.com/mickamy/sampay/gen/user/v1"
	"github.com/mickamy/sampay/internal/domain/user/usecase"
	"github.com/mickamy/sampay/internal/lib/converter"
)

// ToUsecaseSavePaymentMethodInputPtr converts *PaymentMethodInput to *SavePaymentMethodInput.
func ToUsecaseSavePaymentMethodInputPtr(src *userv1.PaymentMethodInput) (*usecase.SavePaymentMethodInput, error) {
	if src == nil {
		return nil, nil
	}

	conv0, err := converter.ToPaymentMethodType(src.Type)
	if err != nil {
		return nil, fmt.Errorf("Type: %w", err)
	}

	return &usecase.SavePaymentMethodInput{
		Type:             conv0,
		URL:              src.Url,
		QRCodeS3ObjectID: converter.StringToPtr(src.QrCodeS3ObjectId),
		DisplayOrder:     converter.Int32ToInt(src.DisplayOrder),
	}, nil

}

// ToUsecaseSavePaymentMethodInput converts PaymentMethodInput to SavePaymentMethodInput.
func ToUsecaseSavePaymentMethodInput(src userv1.PaymentMethodInput) (usecase.SavePaymentMethodInput, error) {

	conv0, err := converter.ToPaymentMethodType(src.Type)
	if err != nil {
		return usecase.SavePaymentMethodInput{}, fmt.Errorf("Type: %w", err)
	}

	return usecase.SavePaymentMethodInput{
		Type:             conv0,
		URL:              src.Url,
		QRCodeS3ObjectID: converter.StringToPtr(src.QrCodeS3ObjectId),
		DisplayOrder:     converter.Int32ToInt(src.DisplayOrder),
	}, nil

}
