// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/auth/model"
)

// OAuthAccounts returns a new Query for the oauth_accounts table.
func OAuthAccounts(db orm.Querier) *orm.Query[model.OAuthAccount] {
	q := orm.NewQuery[model.OAuthAccount](
		db, orm.ResolveTableName[model.OAuthAccount]("oauth_accounts"), oAuthAccountsColumns, "id",
		scanOAuthAccount, oAuthAccountColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setOAuthAccountCreatedAt,
		nil,
		nil,
	)
	return q
}

var oAuthAccountsColumns = []string{"id", "end_user_id", "provider", "uid", "created_at"}

func scanOAuthAccount(rows *sql.Rows) (model.OAuthAccount, error) {
	cols, _ := rows.Columns()
	var v model.OAuthAccount
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "end_user_id":
			dest[i] = &v.EndUserID
		case "provider":
			dest[i] = &v.Provider
		case "uid":
			dest[i] = &v.UID
		case "created_at":
			dest[i] = &v.CreatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func oAuthAccountColumnValuePairs(v *model.OAuthAccount, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "end_user_id", "provider", "uid", "created_at"},
			[]any{v.ID, v.EndUserID, v.Provider, v.UID, v.CreatedAt}
	}
	return []string{"end_user_id", "provider", "uid", "created_at"},
		[]any{v.EndUserID, v.Provider, v.UID, v.CreatedAt}
}

func setOAuthAccountCreatedAt(v *model.OAuthAccount, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
