// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/sampay/internal/di"
	usecase "github.com/mickamy/sampay/internal/domain/event/usecase"
)

// NewEventProfile initializes dependencies and constructs EventProfile.
func NewEventProfile(infra *di.Infra) *EventProfile {
	getEvent := usecase.NewGetEvent(infra)
	joinEvent := usecase.NewJoinEvent(infra)
	claimPayment := usecase.NewClaimPayment(infra)

	return &EventProfile{
		getEvent:     getEvent,
		joinEvent:    joinEvent,
		claimPayment: claimPayment,
	}
}

// MustNewEventProfile initializes dependencies and constructs EventProfile or panics on failure.
func MustNewEventProfile(infra *di.Infra) *EventProfile {
	getEvent := usecase.NewGetEvent(infra)
	joinEvent := usecase.NewJoinEvent(infra)
	claimPayment := usecase.NewClaimPayment(infra)

	return &EventProfile{
		getEvent:     getEvent,
		joinEvent:    joinEvent,
		claimPayment: claimPayment,
	}
}

// NewEventService initializes dependencies and constructs EventService.
func NewEventService(infra *di.Infra) *EventService {
	listMyEvents := usecase.NewListMyEvents(infra)
	createEvent := usecase.NewCreateEvent(infra)
	updateEvent := usecase.NewUpdateEvent(infra)
	deleteEvent := usecase.NewDeleteEvent(infra)
	listEventParticipants := usecase.NewListEventParticipants(infra)
	updateParticipantStatus := usecase.NewUpdateParticipantStatus(infra)
	archiveEvent := usecase.NewArchiveEvent(infra)
	unarchiveEvent := usecase.NewUnarchiveEvent(infra)

	return &EventService{
		listMyEvents:            listMyEvents,
		createEvent:             createEvent,
		updateEvent:             updateEvent,
		deleteEvent:             deleteEvent,
		listEventParticipants:   listEventParticipants,
		updateParticipantStatus: updateParticipantStatus,
		archiveEvent:            archiveEvent,
		unarchiveEvent:          unarchiveEvent,
	}
}

// MustNewEventService initializes dependencies and constructs EventService or panics on failure.
func MustNewEventService(infra *di.Infra) *EventService {
	listMyEvents := usecase.NewListMyEvents(infra)
	createEvent := usecase.NewCreateEvent(infra)
	updateEvent := usecase.NewUpdateEvent(infra)
	deleteEvent := usecase.NewDeleteEvent(infra)
	listEventParticipants := usecase.NewListEventParticipants(infra)
	updateParticipantStatus := usecase.NewUpdateParticipantStatus(infra)
	archiveEvent := usecase.NewArchiveEvent(infra)
	unarchiveEvent := usecase.NewUnarchiveEvent(infra)

	return &EventService{
		listMyEvents:            listMyEvents,
		createEvent:             createEvent,
		updateEvent:             updateEvent,
		deleteEvent:             deleteEvent,
		listEventParticipants:   listEventParticipants,
		updateParticipantStatus: updateParticipantStatus,
		archiveEvent:            archiveEvent,
		unarchiveEvent:          unarchiveEvent,
	}
}
