// Code generated by MockGen. DO NOT EDIT.
// Source: send_message_use_case.go
//
// Generated by this command:
//
//	mockgen -source=send_message_use_case.go -destination=./mock_usecase/mock_send_message_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/message/usecase"
)

// MockSendMessage is a mock of SendMessage interface.
type MockSendMessage struct {
	ctrl     *gomock.Controller
	recorder *MockSendMessageMockRecorder
	isgomock struct{}
}

// MockSendMessageMockRecorder is the mock recorder for MockSendMessage.
type MockSendMessageMockRecorder struct {
	mock *MockSendMessage
}

// NewMockSendMessage creates a new mock instance.
func NewMockSendMessage(ctrl *gomock.Controller) *MockSendMessage {
	mock := &MockSendMessage{ctrl: ctrl}
	mock.recorder = &MockSendMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendMessage) EXPECT() *MockSendMessageMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockSendMessage) Do(ctx context.Context, input usecase.SendMessageInput) (usecase.SendMessageOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.SendMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockSendMessageMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockSendMessage)(nil).Do), ctx, input)
}
