// Code generated by MockGen. DO NOT EDIT.
// Source: create_message_use_case.go
//
// Generated by this command:
//
//	mockgen -source=create_message_use_case.go -destination=./mock_usecase/mock_create_message_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/message/usecase"
)

// MockCreateMessage is a mock of CreateMessage interface.
type MockCreateMessage struct {
	ctrl     *gomock.Controller
	recorder *MockCreateMessageMockRecorder
	isgomock struct{}
}

// MockCreateMessageMockRecorder is the mock recorder for MockCreateMessage.
type MockCreateMessageMockRecorder struct {
	mock *MockCreateMessage
}

// NewMockCreateMessage creates a new mock instance.
func NewMockCreateMessage(ctrl *gomock.Controller) *MockCreateMessage {
	mock := &MockCreateMessage{ctrl: ctrl}
	mock.recorder = &MockCreateMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateMessage) EXPECT() *MockCreateMessageMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCreateMessage) Do(ctx context.Context, input usecase.CreateMessageInput) (usecase.CreateMessageOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CreateMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCreateMessageMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreateMessage)(nil).Do), ctx, input)
}
