// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/ormgen/scope"
	authmodel "github.com/mickamy/sampay/internal/domain/auth/model"
	authquery "github.com/mickamy/sampay/internal/domain/auth/query"
	"github.com/mickamy/sampay/internal/domain/user/model"
)

// EndUsers returns a new Query for the end_users table.
func EndUsers(db orm.Querier) *orm.Query[model.EndUser] {
	q := orm.NewQuery[model.EndUser](
		db, orm.ResolveTableName[model.EndUser]("end_users"), endUsersColumns, "user_id",
		scanEndUser, endUserColumnValuePairs, nil,
	)
	q.RegisterJoin("OAuthAccounts", orm.JoinConfig{
		TargetTable: orm.ResolveTableName[authmodel.OAuthAccount]("oauth_accounts"), TargetColumn: "end_user_id",
		SourceTable: orm.ResolveTableName[model.EndUser]("end_users"), SourceColumn: "user_id",
	})
	q.RegisterPreloader("OAuthAccounts", preloadEndUserOAuthAccounts)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setEndUserCreatedAt,
		[]string{"updated_at"},
		setEndUserUpdatedAt,
	)
	return q
}

var endUsersColumns = []string{"user_id", "slug", "created_at", "updated_at"}

func scanEndUser(rows *sql.Rows) (model.EndUser, error) {
	cols, _ := rows.Columns()
	var v model.EndUser
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "user_id":
			dest[i] = &v.UserID
		case "slug":
			dest[i] = &v.Slug
		case "created_at":
			dest[i] = &v.CreatedAt
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func endUserColumnValuePairs(v *model.EndUser, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"user_id", "slug", "created_at", "updated_at"},
			[]any{v.UserID, v.Slug, v.CreatedAt, v.UpdatedAt}
	}
	return []string{"slug", "created_at", "updated_at"},
		[]any{v.Slug, v.CreatedAt, v.UpdatedAt}
}

func setEndUserCreatedAt(v *model.EndUser, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
func setEndUserUpdatedAt(v *model.EndUser, now time.Time) {
	v.UpdatedAt = now
}
func preloadEndUserOAuthAccounts(ctx context.Context, db orm.Querier, results []model.EndUser) error {
	if len(results) == 0 {
		return nil
	}
	ids := make([]string, len(results))
	for i := range results {
		ids[i] = results[i].UserID
	}
	related, err := authquery.OAuthAccounts(db).Scopes(scope.In("end_user_id", ids)).All(ctx)
	if err != nil {
		return err
	}
	byFK := make(map[string][]authmodel.OAuthAccount)
	for _, r := range related {
		byFK[r.EndUserID] = append(byFK[r.EndUserID], r)
	}
	for i := range results {
		results[i].OAuthAccounts = byFK[results[i].UserID]
	}
	return nil
}
