// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/user/model"
)

// Users returns a new Query for the users table.
func Users(db orm.Querier) *orm.Query[model.User] {
	q := orm.NewQuery[model.User](
		db, orm.ResolveTableName[model.User]("users"), usersColumns, "id",
		scanUser, userColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setUserCreatedAt,
		nil,
		nil,
	)
	return q
}

var usersColumns = []string{"id", "created_at"}

func scanUser(rows *sql.Rows) (model.User, error) {
	cols, _ := rows.Columns()
	var v model.User
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "created_at":
			dest[i] = &v.CreatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func userColumnValuePairs(v *model.User, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "created_at"},
			[]any{v.ID, v.CreatedAt}
	}
	return []string{"created_at"},
		[]any{v.CreatedAt}
}

func setUserCreatedAt(v *model.User, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
