// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/ormgen/scope"
	storagemodel "github.com/mickamy/sampay/internal/domain/storage/model"
	storagequery "github.com/mickamy/sampay/internal/domain/storage/query"
	"github.com/mickamy/sampay/internal/domain/user/model"
)

// UserPaymentMethods returns a new Query for the user_payment_methods table.
func UserPaymentMethods(db orm.Querier) *orm.Query[model.UserPaymentMethod] {
	q := orm.NewQuery[model.UserPaymentMethod](
		db, orm.ResolveTableName[model.UserPaymentMethod]("user_payment_methods"), userPaymentMethodsColumns, "id",
		scanUserPaymentMethod, userPaymentMethodColumnValuePairs, nil,
	)
	q.RegisterJoin("QRCodeS3Object", orm.JoinConfig{
		TargetTable: orm.ResolveTableName[storagemodel.S3Object]("s3_objects"), TargetColumn: "id",
		SourceTable: orm.ResolveTableName[model.UserPaymentMethod]("user_payment_methods"), SourceColumn: "qr_code_s3_object_id",
	})
	q.RegisterPreloader("QRCodeS3Object", preloadUserPaymentMethodQRCodeS3Object)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setUserPaymentMethodCreatedAt,
		[]string{"updated_at"},
		setUserPaymentMethodUpdatedAt,
	)
	return q
}

var userPaymentMethodsColumns = []string{"id", "user_id", "type", "url", "qr_code_s3_object_id", "display_order", "created_at", "updated_at"}

func scanUserPaymentMethod(rows *sql.Rows) (model.UserPaymentMethod, error) {
	cols, _ := rows.Columns()
	var v model.UserPaymentMethod
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "user_id":
			dest[i] = &v.UserID
		case "type":
			dest[i] = &v.Type
		case "url":
			dest[i] = &v.URL
		case "qr_code_s3_object_id":
			dest[i] = &v.QRCodeS3ObjectID
		case "display_order":
			dest[i] = &v.DisplayOrder
		case "created_at":
			dest[i] = &v.CreatedAt
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func userPaymentMethodColumnValuePairs(v *model.UserPaymentMethod, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "user_id", "type", "url", "qr_code_s3_object_id", "display_order", "created_at", "updated_at"},
			[]any{v.ID, v.UserID, v.Type, v.URL, v.QRCodeS3ObjectID, v.DisplayOrder, v.CreatedAt, v.UpdatedAt}
	}
	return []string{"user_id", "type", "url", "qr_code_s3_object_id", "display_order", "created_at", "updated_at"},
		[]any{v.UserID, v.Type, v.URL, v.QRCodeS3ObjectID, v.DisplayOrder, v.CreatedAt, v.UpdatedAt}
}

func setUserPaymentMethodCreatedAt(v *model.UserPaymentMethod, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
func setUserPaymentMethodUpdatedAt(v *model.UserPaymentMethod, now time.Time) {
	v.UpdatedAt = now
}
func preloadUserPaymentMethodQRCodeS3Object(ctx context.Context, db orm.Querier, results []model.UserPaymentMethod) error {
	if len(results) == 0 {
		return nil
	}
	ids := make([]string, 0, len(results))
	for i := range results {
		if results[i].QRCodeS3ObjectID != nil {
			ids = append(ids, *results[i].QRCodeS3ObjectID)
		}
	}
	related, err := storagequery.S3Objects(db).Scopes(scope.In("id", ids)).All(ctx)
	if err != nil {
		return err
	}
	byPK := make(map[string]*storagemodel.S3Object)
	for i := range related {
		byPK[related[i].ID] = &related[i]
	}
	for i := range results {
		if results[i].QRCodeS3ObjectID != nil {
			results[i].QRCodeS3Object = byPK[*results[i].QRCodeS3ObjectID]
		}
	}
	return nil
}
