// Code generated by MockGen. DO NOT EDIT.
// Source: get_user_use_case.go
//
// Generated by this command:
//
//	mockgen -source=get_user_use_case.go -destination=./mock_usecase/mock_get_user_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockGetUser is a mock of GetUser interface.
type MockGetUser struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserMockRecorder
	isgomock struct{}
}

// MockGetUserMockRecorder is the mock recorder for MockGetUser.
type MockGetUserMockRecorder struct {
	mock *MockGetUser
}

// NewMockGetUser creates a new mock instance.
func NewMockGetUser(ctrl *gomock.Controller) *MockGetUser {
	mock := &MockGetUser{ctrl: ctrl}
	mock.recorder = &MockGetUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUser) EXPECT() *MockGetUserMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockGetUser) Do(ctx context.Context, input usecase.GetUserInput) (usecase.GetUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.GetUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGetUserMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetUser)(nil).Do), ctx, input)
}
