// Code generated by MockGen. DO NOT EDIT.
// Source: get_me_use_case.go
//
// Generated by this command:
//
//	mockgen -source=get_me_use_case.go -destination=./mock_usecase/mock_get_me_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockGetMe is a mock of GetMe interface.
type MockGetMe struct {
	ctrl     *gomock.Controller
	recorder *MockGetMeMockRecorder
	isgomock struct{}
}

// MockGetMeMockRecorder is the mock recorder for MockGetMe.
type MockGetMeMockRecorder struct {
	mock *MockGetMe
}

// NewMockGetMe creates a new mock instance.
func NewMockGetMe(ctrl *gomock.Controller) *MockGetMe {
	mock := &MockGetMe{ctrl: ctrl}
	mock.recorder = &MockGetMeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMe) EXPECT() *MockGetMeMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockGetMe) Do(ctx context.Context, input usecase.GetMeInput) (usecase.GetMeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.GetMeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGetMeMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetMe)(nil).Do), ctx, input)
}
