// Code generated by MockGen. DO NOT EDIT.
// Source: update_user_link_qr_code_use_case.go
//
// Generated by this command:
//
//	mockgen -source=update_user_link_qr_code_use_case.go -destination=./mock_usecase/mock_update_user_link_qr_code_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockUpdateUserLinkQRCode is a mock of UpdateUserLinkQRCode interface.
type MockUpdateUserLinkQRCode struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserLinkQRCodeMockRecorder
	isgomock struct{}
}

// MockUpdateUserLinkQRCodeMockRecorder is the mock recorder for MockUpdateUserLinkQRCode.
type MockUpdateUserLinkQRCodeMockRecorder struct {
	mock *MockUpdateUserLinkQRCode
}

// NewMockUpdateUserLinkQRCode creates a new mock instance.
func NewMockUpdateUserLinkQRCode(ctrl *gomock.Controller) *MockUpdateUserLinkQRCode {
	mock := &MockUpdateUserLinkQRCode{ctrl: ctrl}
	mock.recorder = &MockUpdateUserLinkQRCodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserLinkQRCode) EXPECT() *MockUpdateUserLinkQRCodeMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUpdateUserLinkQRCode) Do(ctx context.Context, input usecase.UpdateUserLinkQRCodeInput) (usecase.UpdateUserLinkQRCodeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.UpdateUserLinkQRCodeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockUpdateUserLinkQRCodeMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUpdateUserLinkQRCode)(nil).Do), ctx, input)
}
