// Code generated by MockGen. DO NOT EDIT.
// Source: delete_user_link_use_case.go
//
// Generated by this command:
//
//	mockgen -source=delete_user_link_use_case.go -destination=./mock_usecase/mock_delete_user_link_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockDeleteUserLink is a mock of DeleteUserLink interface.
type MockDeleteUserLink struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserLinkMockRecorder
	isgomock struct{}
}

// MockDeleteUserLinkMockRecorder is the mock recorder for MockDeleteUserLink.
type MockDeleteUserLinkMockRecorder struct {
	mock *MockDeleteUserLink
}

// NewMockDeleteUserLink creates a new mock instance.
func NewMockDeleteUserLink(ctrl *gomock.Controller) *MockDeleteUserLink {
	mock := &MockDeleteUserLink{ctrl: ctrl}
	mock.recorder = &MockDeleteUserLinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUserLink) EXPECT() *MockDeleteUserLinkMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockDeleteUserLink) Do(ctx context.Context, input usecase.DeleteUserLinkInput) (usecase.DeleteUserLinkOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.DeleteUserLinkOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockDeleteUserLinkMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDeleteUserLink)(nil).Do), ctx, input)
}
