// Code generated by MockGen. DO NOT EDIT.
// Source: update_user_profile_use_case.go
//
// Generated by this command:
//
//	mockgen -source=update_user_profile_use_case.go -destination=./mock_usecase/mock_update_user_profile_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockUpdateUserProfile is a mock of UpdateUserProfile interface.
type MockUpdateUserProfile struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserProfileMockRecorder
	isgomock struct{}
}

// MockUpdateUserProfileMockRecorder is the mock recorder for MockUpdateUserProfile.
type MockUpdateUserProfileMockRecorder struct {
	mock *MockUpdateUserProfile
}

// NewMockUpdateUserProfile creates a new mock instance.
func NewMockUpdateUserProfile(ctrl *gomock.Controller) *MockUpdateUserProfile {
	mock := &MockUpdateUserProfile{ctrl: ctrl}
	mock.recorder = &MockUpdateUserProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserProfile) EXPECT() *MockUpdateUserProfileMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUpdateUserProfile) Do(ctx context.Context, input usecase.UpdateUserProfileInput) (usecase.UpdateUserProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.UpdateUserProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockUpdateUserProfileMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUpdateUserProfile)(nil).Do), ctx, input)
}
