// Code generated by MockGen. DO NOT EDIT.
// Source: update_user_profile_image_use_case.go
//
// Generated by this command:
//
//	mockgen -source=update_user_profile_image_use_case.go -destination=./mock_usecase/mock_update_user_profile_image_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/user/usecase"
)

// MockUpdateUserProfileImage is a mock of UpdateUserProfileImage interface.
type MockUpdateUserProfileImage struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserProfileImageMockRecorder
	isgomock struct{}
}

// MockUpdateUserProfileImageMockRecorder is the mock recorder for MockUpdateUserProfileImage.
type MockUpdateUserProfileImageMockRecorder struct {
	mock *MockUpdateUserProfileImage
}

// NewMockUpdateUserProfileImage creates a new mock instance.
func NewMockUpdateUserProfileImage(ctrl *gomock.Controller) *MockUpdateUserProfileImage {
	mock := &MockUpdateUserProfileImage{ctrl: ctrl}
	mock.recorder = &MockUpdateUserProfileImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserProfileImage) EXPECT() *MockUpdateUserProfileImageMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUpdateUserProfileImage) Do(ctx context.Context, input usecase.UpdateUserProfileImageInput) (usecase.UpdateUserProfileImageOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.UpdateUserProfileImageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockUpdateUserProfileImageMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUpdateUserProfileImage)(nil).Do), ctx, input)
}
