CREATE DATABASE sampay;
\c sampay;

GRANT USAGE ON SCHEMA public TO sampay_writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sampay_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sampay_writer;
GRANT CREATE ON SCHEMA public TO sampay_writer;
