// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/user/repository"
)

// NewListPaymentMethods initializes dependencies and constructs listPaymentMethods.
func NewListPaymentMethods(infra *di.Infra) ListPaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &listPaymentMethods{
		reader:            infra.ReaderDB,
		paymentMethodRepo: userPaymentMethod,
	}
}

// MustNewListPaymentMethods initializes dependencies and constructs listPaymentMethods or panics on failure.
func MustNewListPaymentMethods(infra *di.Infra) ListPaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &listPaymentMethods{
		reader:            infra.ReaderDB,
		paymentMethodRepo: userPaymentMethod,
	}
}

// NewSavePaymentMethods initializes dependencies and constructs savePaymentMethods.
func NewSavePaymentMethods(infra *di.Infra) SavePaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &savePaymentMethods{
		writer:            infra.WriterDB,
		paymentMethodRepo: userPaymentMethod,
	}
}

// MustNewSavePaymentMethods initializes dependencies and constructs savePaymentMethods or panics on failure.
func MustNewSavePaymentMethods(infra *di.Infra) SavePaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &savePaymentMethods{
		writer:            infra.WriterDB,
		paymentMethodRepo: userPaymentMethod,
	}
}
