// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository2 "github.com/mickamy/sampay/internal/domain/storage/repository"
	repository "github.com/mickamy/sampay/internal/domain/user/repository"
)

// NewCheckSlugAvailability initializes dependencies and constructs checkSlugAvailability.
func NewCheckSlugAvailability(infra *di.Infra) CheckSlugAvailability {
	endUser := repository.NewEndUser(infra.DB)

	return &checkSlugAvailability{
		reader:      infra.ReaderDB,
		endUserRepo: endUser,
	}
}

// MustNewCheckSlugAvailability initializes dependencies and constructs checkSlugAvailability or panics on failure.
func MustNewCheckSlugAvailability(infra *di.Infra) CheckSlugAvailability {
	endUser := repository.NewEndUser(infra.DB)

	return &checkSlugAvailability{
		reader:      infra.ReaderDB,
		endUserRepo: endUser,
	}
}

// NewGetMe initializes dependencies and constructs getMe.
func NewGetMe(infra *di.Infra) GetMe {
	endUser := repository.NewEndUser(infra.DB)

	return &getMe{
		reader:      infra.ReaderDB,
		endUserRepo: endUser,
	}
}

// MustNewGetMe initializes dependencies and constructs getMe or panics on failure.
func MustNewGetMe(infra *di.Infra) GetMe {
	endUser := repository.NewEndUser(infra.DB)

	return &getMe{
		reader:      infra.ReaderDB,
		endUserRepo: endUser,
	}
}

// NewGetUserProfile initializes dependencies and constructs getUserProfile.
func NewGetUserProfile(infra *di.Infra) GetUserProfile {
	endUser := repository.NewEndUser(infra.DB)
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &getUserProfile{
		reader:            infra.ReaderDB,
		endUserRepo:       endUser,
		paymentMethodRepo: userPaymentMethod,
	}
}

// MustNewGetUserProfile initializes dependencies and constructs getUserProfile or panics on failure.
func MustNewGetUserProfile(infra *di.Infra) GetUserProfile {
	endUser := repository.NewEndUser(infra.DB)
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &getUserProfile{
		reader:            infra.ReaderDB,
		endUserRepo:       endUser,
		paymentMethodRepo: userPaymentMethod,
	}
}

// NewListPaymentMethods initializes dependencies and constructs listPaymentMethods.
func NewListPaymentMethods(infra *di.Infra) ListPaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &listPaymentMethods{
		reader:            infra.ReaderDB,
		paymentMethodRepo: userPaymentMethod,
	}
}

// MustNewListPaymentMethods initializes dependencies and constructs listPaymentMethods or panics on failure.
func MustNewListPaymentMethods(infra *di.Infra) ListPaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)

	return &listPaymentMethods{
		reader:            infra.ReaderDB,
		paymentMethodRepo: userPaymentMethod,
	}
}

// NewSavePaymentMethods initializes dependencies and constructs savePaymentMethods.
func NewSavePaymentMethods(infra *di.Infra) SavePaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)
	s3Object := repository2.NewS3Object(infra.DB)

	return &savePaymentMethods{
		writer:            infra.WriterDB,
		paymentMethodRepo: userPaymentMethod,
		s3ObjRepo:         s3Object,
	}
}

// MustNewSavePaymentMethods initializes dependencies and constructs savePaymentMethods or panics on failure.
func MustNewSavePaymentMethods(infra *di.Infra) SavePaymentMethods {
	userPaymentMethod := repository.NewUserPaymentMethod(infra.DB)
	s3Object := repository2.NewS3Object(infra.DB)

	return &savePaymentMethods{
		writer:            infra.WriterDB,
		paymentMethodRepo: userPaymentMethod,
		s3ObjRepo:         s3Object,
	}
}

// NewUpdateSlug initializes dependencies and constructs updateSlug.
func NewUpdateSlug(infra *di.Infra) UpdateSlug {
	endUser := repository.NewEndUser(infra.DB)

	return &updateSlug{
		writer:      infra.WriterDB,
		endUserRepo: endUser,
	}
}

// MustNewUpdateSlug initializes dependencies and constructs updateSlug or panics on failure.
func MustNewUpdateSlug(infra *di.Infra) UpdateSlug {
	endUser := repository.NewEndUser(infra.DB)

	return &updateSlug{
		writer:      infra.WriterDB,
		endUserRepo: endUser,
	}
}
