// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/messaging/model"
)

// LineFriendships returns a new Query for the line_friendships table.
func LineFriendships(db orm.Querier) *orm.Query[model.LineFriendship] {
	q := orm.NewQuery[model.LineFriendship](
		db, orm.ResolveTableName[model.LineFriendship]("line_friendships"), lineFriendshipsColumns, "end_user_id",
		scanLineFriendship, lineFriendshipColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		nil,
		nil,
		[]string{"updated_at"},
		setLineFriendshipUpdatedAt,
	)
	return q
}

var lineFriendshipsColumns = []string{"end_user_id", "is_friend", "updated_at"}

func scanLineFriendship(rows *sql.Rows) (model.LineFriendship, error) {
	cols, _ := rows.Columns()
	var v model.LineFriendship
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "end_user_id":
			dest[i] = &v.EndUserID
		case "is_friend":
			dest[i] = &v.IsFriend
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func lineFriendshipColumnValuePairs(v *model.LineFriendship, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"end_user_id", "is_friend", "updated_at"},
			[]any{v.EndUserID, v.IsFriend, v.UpdatedAt}
	}
	return []string{"is_friend", "updated_at"},
		[]any{v.IsFriend, v.UpdatedAt}
}

func setLineFriendshipUpdatedAt(v *model.LineFriendship, now time.Time) {
	v.UpdatedAt = now
}
