// Code generated by MockGen. DO NOT EDIT.
// Source: create_password_use_case.go
//
// Generated by this command:
//
//	mockgen -source=create_password_use_case.go -destination=./mock_usecase/mock_create_password_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockCreatePassword is a mock of CreatePassword interface.
type MockCreatePassword struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePasswordMockRecorder
	isgomock struct{}
}

// MockCreatePasswordMockRecorder is the mock recorder for MockCreatePassword.
type MockCreatePasswordMockRecorder struct {
	mock *MockCreatePassword
}

// NewMockCreatePassword creates a new mock instance.
func NewMockCreatePassword(ctrl *gomock.Controller) *MockCreatePassword {
	mock := &MockCreatePassword{ctrl: ctrl}
	mock.recorder = &MockCreatePasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePassword) EXPECT() *MockCreatePasswordMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCreatePassword) Do(ctx context.Context, input usecase.CreatePasswordInput) (usecase.CreatePasswordOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CreatePasswordOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCreatePasswordMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreatePassword)(nil).Do), ctx, input)
}
