// Code generated by MockGen. DO NOT EDIT.
// Source: get_onboarding_step_use_case.go
//
// Generated by this command:
//
//	mockgen -source=get_onboarding_step_use_case.go -destination=./mock_usecase/mock_get_onboarding_step_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockGetOnboardingStep is a mock of GetOnboardingStep interface.
type MockGetOnboardingStep struct {
	ctrl     *gomock.Controller
	recorder *MockGetOnboardingStepMockRecorder
	isgomock struct{}
}

// MockGetOnboardingStepMockRecorder is the mock recorder for MockGetOnboardingStep.
type MockGetOnboardingStepMockRecorder struct {
	mock *MockGetOnboardingStep
}

// NewMockGetOnboardingStep creates a new mock instance.
func NewMockGetOnboardingStep(ctrl *gomock.Controller) *MockGetOnboardingStep {
	mock := &MockGetOnboardingStep{ctrl: ctrl}
	mock.recorder = &MockGetOnboardingStepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetOnboardingStep) EXPECT() *MockGetOnboardingStepMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockGetOnboardingStep) Do(ctx context.Context, input usecase.GetOnboardingStepInput) (usecase.GetOnboardingStepOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.GetOnboardingStepOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGetOnboardingStepMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetOnboardingStep)(nil).Do), ctx, input)
}
