// Code generated by MockGen. DO NOT EDIT.
// Source: update_user_attribute_use_case.go
//
// Generated by this command:
//
//	mockgen -source=update_user_attribute_use_case.go -destination=./mock_usecase/mock_update_user_attribute_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockUpdateUserAttribute is a mock of UpdateUserAttribute interface.
type MockUpdateUserAttribute struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserAttributeMockRecorder
	isgomock struct{}
}

// MockUpdateUserAttributeMockRecorder is the mock recorder for MockUpdateUserAttribute.
type MockUpdateUserAttributeMockRecorder struct {
	mock *MockUpdateUserAttribute
}

// NewMockUpdateUserAttribute creates a new mock instance.
func NewMockUpdateUserAttribute(ctrl *gomock.Controller) *MockUpdateUserAttribute {
	mock := &MockUpdateUserAttribute{ctrl: ctrl}
	mock.recorder = &MockUpdateUserAttributeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserAttribute) EXPECT() *MockUpdateUserAttributeMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUpdateUserAttribute) Do(ctx context.Context, input usecase.UpdateUserAttributeInput) (usecase.UpdateUserAttributeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.UpdateUserAttributeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockUpdateUserAttributeMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUpdateUserAttribute)(nil).Do), ctx, input)
}
