// Code generated by MockGen. DO NOT EDIT.
// Source: create_user_attribute_use_case.go
//
// Generated by this command:
//
//	mockgen -source=create_user_attribute_use_case.go -destination=./mock_usecase/mock_create_user_attribute_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockCreateUserAttribute is a mock of CreateUserAttribute interface.
type MockCreateUserAttribute struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserAttributeMockRecorder
	isgomock struct{}
}

// MockCreateUserAttributeMockRecorder is the mock recorder for MockCreateUserAttribute.
type MockCreateUserAttributeMockRecorder struct {
	mock *MockCreateUserAttribute
}

// NewMockCreateUserAttribute creates a new mock instance.
func NewMockCreateUserAttribute(ctrl *gomock.Controller) *MockCreateUserAttribute {
	mock := &MockCreateUserAttribute{ctrl: ctrl}
	mock.recorder = &MockCreateUserAttributeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserAttribute) EXPECT() *MockCreateUserAttributeMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCreateUserAttribute) Do(ctx context.Context, input usecase.CreateUserAttributeInput) (usecase.CreateUserAttributeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CreateUserAttributeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCreateUserAttributeMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreateUserAttribute)(nil).Do), ctx, input)
}
