// Code generated by MockGen. DO NOT EDIT.
// Source: update_user_links_use_case.go
//
// Generated by this command:
//
//	mockgen -source=update_user_links_use_case.go -destination=./mock_usecase/mock_update_user_links_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockUpdateUserLinks is a mock of UpdateUserLinks interface.
type MockUpdateUserLinks struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserLinksMockRecorder
	isgomock struct{}
}

// MockUpdateUserLinksMockRecorder is the mock recorder for MockUpdateUserLinks.
type MockUpdateUserLinksMockRecorder struct {
	mock *MockUpdateUserLinks
}

// NewMockUpdateUserLinks creates a new mock instance.
func NewMockUpdateUserLinks(ctrl *gomock.Controller) *MockUpdateUserLinks {
	mock := &MockUpdateUserLinks{ctrl: ctrl}
	mock.recorder = &MockUpdateUserLinksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserLinks) EXPECT() *MockUpdateUserLinksMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockUpdateUserLinks) Do(ctx context.Context, input usecase.UpdateUserLinksInput) (usecase.UpdateUserLinksOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.UpdateUserLinksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockUpdateUserLinksMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockUpdateUserLinks)(nil).Do), ctx, input)
}
