// Code generated by MockGen. DO NOT EDIT.
// Source: create_user_profile_use_case.go
//
// Generated by this command:
//
//	mockgen -source=create_user_profile_use_case.go -destination=./mock_usecase/mock_create_user_profile_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockCreateUserProfile is a mock of CreateUserProfile interface.
type MockCreateUserProfile struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserProfileMockRecorder
	isgomock struct{}
}

// MockCreateUserProfileMockRecorder is the mock recorder for MockCreateUserProfile.
type MockCreateUserProfileMockRecorder struct {
	mock *MockCreateUserProfile
}

// NewMockCreateUserProfile creates a new mock instance.
func NewMockCreateUserProfile(ctrl *gomock.Controller) *MockCreateUserProfile {
	mock := &MockCreateUserProfile{ctrl: ctrl}
	mock.recorder = &MockCreateUserProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserProfile) EXPECT() *MockCreateUserProfileMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCreateUserProfile) Do(ctx context.Context, input usecase.CreateUserProfileInput) (usecase.CreateUserProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CreateUserProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCreateUserProfileMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreateUserProfile)(nil).Do), ctx, input)
}
