// Code generated by MockGen. DO NOT EDIT.
// Source: verify_email_use_case.go
//
// Generated by this command:
//
//	mockgen -source=verify_email_use_case.go -destination=./mock_usecase/mock_verify_email_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockVerifyEmail is a mock of VerifyEmail interface.
type MockVerifyEmail struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyEmailMockRecorder
	isgomock struct{}
}

// MockVerifyEmailMockRecorder is the mock recorder for MockVerifyEmail.
type MockVerifyEmailMockRecorder struct {
	mock *MockVerifyEmail
}

// NewMockVerifyEmail creates a new mock instance.
func NewMockVerifyEmail(ctrl *gomock.Controller) *MockVerifyEmail {
	mock := &MockVerifyEmail{ctrl: ctrl}
	mock.recorder = &MockVerifyEmailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyEmail) EXPECT() *MockVerifyEmailMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockVerifyEmail) Do(ctx context.Context, input usecase.VerifyEmailInput) (usecase.VerifyEmailOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.VerifyEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockVerifyEmailMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockVerifyEmail)(nil).Do), ctx, input)
}
