// Code generated by MockGen. DO NOT EDIT.
// Source: request_email_verification_use_case.go
//
// Generated by this command:
//
//	mockgen -source=request_email_verification_use_case.go -destination=./mock_usecase/mock_request_email_verification_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/registration/usecase"
)

// MockRequestEmailVerification is a mock of RequestEmailVerification interface.
type MockRequestEmailVerification struct {
	ctrl     *gomock.Controller
	recorder *MockRequestEmailVerificationMockRecorder
	isgomock struct{}
}

// MockRequestEmailVerificationMockRecorder is the mock recorder for MockRequestEmailVerification.
type MockRequestEmailVerificationMockRecorder struct {
	mock *MockRequestEmailVerification
}

// NewMockRequestEmailVerification creates a new mock instance.
func NewMockRequestEmailVerification(ctrl *gomock.Controller) *MockRequestEmailVerification {
	mock := &MockRequestEmailVerification{ctrl: ctrl}
	mock.recorder = &MockRequestEmailVerificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestEmailVerification) EXPECT() *MockRequestEmailVerificationMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockRequestEmailVerification) Do(ctx context.Context, input usecase.RequestEmailVerificationInput) (usecase.RequestEmailVerificationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.RequestEmailVerificationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockRequestEmailVerificationMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockRequestEmailVerification)(nil).Do), ctx, input)
}
