// Code generated by MockGen. DO NOT EDIT.
// Source: reset_password_use_case.go
//
// Generated by this command:
//
//	mockgen -source=reset_password_use_case.go -destination=./mock_usecase/mock_reset_password_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockResetPassword is a mock of ResetPassword interface.
type MockResetPassword struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordMockRecorder
	isgomock struct{}
}

// MockResetPasswordMockRecorder is the mock recorder for MockResetPassword.
type MockResetPasswordMockRecorder struct {
	mock *MockResetPassword
}

// NewMockResetPassword creates a new mock instance.
func NewMockResetPassword(ctrl *gomock.Controller) *MockResetPassword {
	mock := &MockResetPassword{ctrl: ctrl}
	mock.recorder = &MockResetPasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPassword) EXPECT() *MockResetPasswordMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockResetPassword) Do(ctx context.Context, input usecase.ResetPasswordInput) (usecase.ResetPasswordOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.ResetPasswordOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockResetPasswordMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockResetPassword)(nil).Do), ctx, input)
}
