// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_session_use_case.go
//
// Generated by this command:
//
//	mockgen -source=refresh_session_use_case.go -destination=./mock_usecase/mock_refresh_session_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockRefreshSession is a mock of RefreshSession interface.
type MockRefreshSession struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionMockRecorder
	isgomock struct{}
}

// MockRefreshSessionMockRecorder is the mock recorder for MockRefreshSession.
type MockRefreshSessionMockRecorder struct {
	mock *MockRefreshSession
}

// NewMockRefreshSession creates a new mock instance.
func NewMockRefreshSession(ctrl *gomock.Controller) *MockRefreshSession {
	mock := &MockRefreshSession{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSession) EXPECT() *MockRefreshSessionMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockRefreshSession) Do(ctx context.Context, input usecase.RefreshSessionInput) (usecase.RefreshSessionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.RefreshSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockRefreshSessionMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockRefreshSession)(nil).Do), ctx, input)
}
