// Code generated by MockGen. DO NOT EDIT.
// Source: authenticate_user_use_case.go
//
// Generated by this command:
//
//	mockgen -source=authenticate_user_use_case.go -destination=./mock_usecase/mock_authenticate_user_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockAuthenticateUser is a mock of AuthenticateUser interface.
type MockAuthenticateUser struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticateUserMockRecorder
	isgomock struct{}
}

// MockAuthenticateUserMockRecorder is the mock recorder for MockAuthenticateUser.
type MockAuthenticateUserMockRecorder struct {
	mock *MockAuthenticateUser
}

// NewMockAuthenticateUser creates a new mock instance.
func NewMockAuthenticateUser(ctrl *gomock.Controller) *MockAuthenticateUser {
	mock := &MockAuthenticateUser{ctrl: ctrl}
	mock.recorder = &MockAuthenticateUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticateUser) EXPECT() *MockAuthenticateUserMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockAuthenticateUser) Do(ctx context.Context, input usecase.AuthenticateUserInput) (usecase.AuthenticateUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.AuthenticateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockAuthenticateUserMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockAuthenticateUser)(nil).Do), ctx, input)
}
