// Code generated by MockGen. DO NOT EDIT.
// Source: authenticate_anonymous_user_use_case.go
//
// Generated by this command:
//
//	mockgen -source=authenticate_anonymous_user_use_case.go -destination=./mock_usecase/mock_authenticate_anonymous_user_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockAuthenticateAnonymousUser is a mock of AuthenticateAnonymousUser interface.
type MockAuthenticateAnonymousUser struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticateAnonymousUserMockRecorder
	isgomock struct{}
}

// MockAuthenticateAnonymousUserMockRecorder is the mock recorder for MockAuthenticateAnonymousUser.
type MockAuthenticateAnonymousUserMockRecorder struct {
	mock *MockAuthenticateAnonymousUser
}

// NewMockAuthenticateAnonymousUser creates a new mock instance.
func NewMockAuthenticateAnonymousUser(ctrl *gomock.Controller) *MockAuthenticateAnonymousUser {
	mock := &MockAuthenticateAnonymousUser{ctrl: ctrl}
	mock.recorder = &MockAuthenticateAnonymousUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticateAnonymousUser) EXPECT() *MockAuthenticateAnonymousUserMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockAuthenticateAnonymousUser) Do(ctx context.Context, input usecase.AuthenticateAnonymousUserInput) (usecase.AuthenticateAnonymousUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.AuthenticateAnonymousUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockAuthenticateAnonymousUserMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockAuthenticateAnonymousUser)(nil).Do), ctx, input)
}
