// Code generated by MockGen. DO NOT EDIT.
// Source: create_session_use_case.go
//
// Generated by this command:
//
//	mockgen -source=create_session_use_case.go -destination=./mock_usecase/mock_create_session_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockCreateSession is a mock of CreateSession interface.
type MockCreateSession struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSessionMockRecorder
	isgomock struct{}
}

// MockCreateSessionMockRecorder is the mock recorder for MockCreateSession.
type MockCreateSessionMockRecorder struct {
	mock *MockCreateSession
}

// NewMockCreateSession creates a new mock instance.
func NewMockCreateSession(ctrl *gomock.Controller) *MockCreateSession {
	mock := &MockCreateSession{ctrl: ctrl}
	mock.recorder = &MockCreateSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSession) EXPECT() *MockCreateSessionMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCreateSession) Do(ctx context.Context, input usecase.CreateSessionInput) (usecase.CreateSessionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CreateSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCreateSessionMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCreateSession)(nil).Do), ctx, input)
}
