// Code generated by MockGen. DO NOT EDIT.
// Source: delete_session_use_case.go
//
// Generated by this command:
//
//	mockgen -source=delete_session_use_case.go -destination=./mock_usecase/mock_delete_session_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/auth/usecase"
)

// MockDeleteSession is a mock of DeleteSession interface.
type MockDeleteSession struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteSessionMockRecorder
	isgomock struct{}
}

// MockDeleteSessionMockRecorder is the mock recorder for MockDeleteSession.
type MockDeleteSessionMockRecorder struct {
	mock *MockDeleteSession
}

// NewMockDeleteSession creates a new mock instance.
func NewMockDeleteSession(ctrl *gomock.Controller) *MockDeleteSession {
	mock := &MockDeleteSession{ctrl: ctrl}
	mock.recorder = &MockDeleteSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteSession) EXPECT() *MockDeleteSessionMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockDeleteSession) Do(ctx context.Context, input usecase.DeleteSessionInput) (usecase.DeleteSessionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.DeleteSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockDeleteSessionMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDeleteSession)(nil).Do), ctx, input)
}
