// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/sampay/internal/di"
	usecase "github.com/mickamy/sampay/internal/domain/user/usecase"
)

// NewPaymentMethod initializes dependencies and constructs PaymentMethod.
func NewPaymentMethod(infra *di.Infra) *PaymentMethod {
	listPaymentMethods := usecase.NewListPaymentMethods(infra)
	savePaymentMethods := usecase.NewSavePaymentMethods(infra)

	return &PaymentMethod{
		listPaymentMethods: listPaymentMethods,
		savePaymentMethods: savePaymentMethods,
	}
}

// MustNewPaymentMethod initializes dependencies and constructs PaymentMethod or panics on failure.
func MustNewPaymentMethod(infra *di.Infra) *PaymentMethod {
	listPaymentMethods := usecase.NewListPaymentMethods(infra)
	savePaymentMethods := usecase.NewSavePaymentMethods(infra)

	return &PaymentMethod{
		listPaymentMethods: listPaymentMethods,
		savePaymentMethods: savePaymentMethods,
	}
}
