// Code generated by injector. DO NOT EDIT.

package handler

import (
	di "github.com/mickamy/sampay/internal/di"
	usecase "github.com/mickamy/sampay/internal/domain/storage/usecase"
)

// NewStorage initializes dependencies and constructs Storage.
func NewStorage(infra *di.Infra) *Storage {
	getUploadURL := usecase.NewGetUploadURL(infra)

	return &Storage{
		getUploadURL: getUploadURL,
	}
}

// MustNewStorage initializes dependencies and constructs Storage or panics on failure.
func MustNewStorage(infra *di.Infra) *Storage {
	getUploadURL := usecase.NewGetUploadURL(infra)

	return &Storage{
		getUploadURL: getUploadURL,
	}
}
