// Code generated by MockGen. DO NOT EDIT.
// Source: count_unread_notifications_use_case.go
//
// Generated by this command:
//
//	mockgen -source=count_unread_notifications_use_case.go -destination=./mock_usecase/mock_count_unread_notifications_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/notification/usecase"
)

// MockCountUnreadNotifications is a mock of CountUnreadNotifications interface.
type MockCountUnreadNotifications struct {
	ctrl     *gomock.Controller
	recorder *MockCountUnreadNotificationsMockRecorder
	isgomock struct{}
}

// MockCountUnreadNotificationsMockRecorder is the mock recorder for MockCountUnreadNotifications.
type MockCountUnreadNotificationsMockRecorder struct {
	mock *MockCountUnreadNotifications
}

// NewMockCountUnreadNotifications creates a new mock instance.
func NewMockCountUnreadNotifications(ctrl *gomock.Controller) *MockCountUnreadNotifications {
	mock := &MockCountUnreadNotifications{ctrl: ctrl}
	mock.recorder = &MockCountUnreadNotificationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountUnreadNotifications) EXPECT() *MockCountUnreadNotificationsMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockCountUnreadNotifications) Do(ctx context.Context, input usecase.CountUnreadNotificationsInput) (usecase.CountUnreadNotificationsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.CountUnreadNotificationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockCountUnreadNotificationsMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockCountUnreadNotifications)(nil).Do), ctx, input)
}
