// Code generated by MockGen. DO NOT EDIT.
// Source: read_notification_use_case.go
//
// Generated by this command:
//
//	mockgen -source=read_notification_use_case.go -destination=./mock_usecase/mock_read_notification_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/notification/usecase"
)

// MockReadNotification is a mock of ReadNotification interface.
type MockReadNotification struct {
	ctrl     *gomock.Controller
	recorder *MockReadNotificationMockRecorder
	isgomock struct{}
}

// MockReadNotificationMockRecorder is the mock recorder for MockReadNotification.
type MockReadNotificationMockRecorder struct {
	mock *MockReadNotification
}

// NewMockReadNotification creates a new mock instance.
func NewMockReadNotification(ctrl *gomock.Controller) *MockReadNotification {
	mock := &MockReadNotification{ctrl: ctrl}
	mock.recorder = &MockReadNotificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadNotification) EXPECT() *MockReadNotificationMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockReadNotification) Do(ctx context.Context, input usecase.ReadNotificationInput) (usecase.ReadNotificationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.ReadNotificationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockReadNotificationMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockReadNotification)(nil).Do), ctx, input)
}
