// Code generated by MockGen. DO NOT EDIT.
// Source: user_profile_repository.go
//
// Generated by this command:
//
//	mockgen -source=user_profile_repository.go -destination=./mock_repository/mock_user_profile_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	database "mickamy.com/sampay/internal/cli/infra/storage/database"
	model "mickamy.com/sampay/internal/domain/user/model"
	repository "mickamy.com/sampay/internal/domain/user/repository"
)

// MockUserProfile is a mock of UserProfile interface.
type MockUserProfile struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileMockRecorder
	isgomock struct{}
}

// MockUserProfileMockRecorder is the mock recorder for MockUserProfile.
type MockUserProfileMockRecorder struct {
	mock *MockUserProfile
}

// NewMockUserProfile creates a new mock instance.
func NewMockUserProfile(ctrl *gomock.Controller) *MockUserProfile {
	mock := &MockUserProfile{ctrl: ctrl}
	mock.recorder = &MockUserProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfile) EXPECT() *MockUserProfileMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockUserProfile) Create(ctx context.Context, m *model.UserProfile) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfile)(nil).Create), ctx, m)
}

// Find mocks base method.
func (m *MockUserProfile) Find(ctx context.Context, id string, scopes ...database.Scope) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range scopes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserProfileMockRecorder) Find(ctx, id any, scopes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, scopes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserProfile)(nil).Find), varargs...)
}

// FindBySlug mocks base method.
func (m *MockUserProfile) FindBySlug(ctx context.Context, slug string, scopes ...database.Scope) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, slug}
	for _, a := range scopes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindBySlug", varargs...)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockUserProfileMockRecorder) FindBySlug(ctx, slug any, scopes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, slug}, scopes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockUserProfile)(nil).FindBySlug), varargs...)
}

// Update mocks base method.
func (m_2 *MockUserProfile) Update(ctx context.Context, m *model.UserProfile) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileMockRecorder) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfile)(nil).Update), ctx, m)
}

// WithTx mocks base method.
func (m *MockUserProfile) WithTx(tx *database.DB) repository.UserProfile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.UserProfile)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserProfileMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserProfile)(nil).WithTx), tx)
}
