CREATE TABLE users
(
    id         CHAR(26)    NOT NULL PRIMARY KEY,
    slug       VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_slug UNIQUE (slug)
);
