-- migrate:up
ALTER
    DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sampay_writer;

ALTER
    DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO sampay_reader;

-- migrate:down
ALTER
    DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM sampay_writer;

ALTER
    DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT ON TABLES FROM sampay_reader;
