// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/auth/repository"
	repository2 "github.com/mickamy/sampay/internal/domain/user/repository"
	oauth "github.com/mickamy/sampay/internal/lib/oauth"
)

// NewAuthenticate initializes dependencies and constructs authenticate.
func NewAuthenticate(infra *di.Infra) Authenticate {
	session := repository.NewSession(infra.KVS)

	return &authenticate{
		sessionRepo: session,
	}
}

// MustNewAuthenticate initializes dependencies and constructs authenticate or panics on failure.
func MustNewAuthenticate(infra *di.Infra) Authenticate {
	session := repository.NewSession(infra.KVS)

	return &authenticate{
		sessionRepo: session,
	}
}

// NewGetOAuthURL initializes dependencies and constructs getOAuthURL.
func NewGetOAuthURL(resolver *oauth.Resolver) GetOAuthURL {

	return &getOAuthURL{
		resolver: resolver,
	}
}

// MustNewGetOAuthURL initializes dependencies and constructs getOAuthURL or panics on failure.
func MustNewGetOAuthURL(resolver *oauth.Resolver) GetOAuthURL {

	return &getOAuthURL{
		resolver: resolver,
	}
}

// NewLogout initializes dependencies and constructs logout.
func NewLogout(infra *di.Infra) Logout {
	session := repository.NewSession(infra.KVS)

	return &logout{
		sessionRepo: session,
	}
}

// MustNewLogout initializes dependencies and constructs logout or panics on failure.
func MustNewLogout(infra *di.Infra) Logout {
	session := repository.NewSession(infra.KVS)

	return &logout{
		sessionRepo: session,
	}
}

// NewOAuthCallback initializes dependencies and constructs oauthCallback.
func NewOAuthCallback(infra *di.Infra, resolver *oauth.Resolver) OAuthCallback {
	user := repository2.NewUser(infra.DB)
	endUser := repository2.NewEndUser(infra.DB)
	oAuthAccount := repository.NewOAuthAccount(infra.DB)
	session := repository.NewSession(infra.KVS)

	return &oauthCallback{
		resolver:         resolver,
		writer:           infra.WriterDB,
		userRepo:         user,
		endUserRepo:      endUser,
		oauthAccountRepo: oAuthAccount,
		sessionRepo:      session,
	}
}

// MustNewOAuthCallback initializes dependencies and constructs oauthCallback or panics on failure.
func MustNewOAuthCallback(infra *di.Infra, resolver *oauth.Resolver) OAuthCallback {
	user := repository2.NewUser(infra.DB)
	endUser := repository2.NewEndUser(infra.DB)
	oAuthAccount := repository.NewOAuthAccount(infra.DB)
	session := repository.NewSession(infra.KVS)

	return &oauthCallback{
		resolver:         resolver,
		writer:           infra.WriterDB,
		userRepo:         user,
		endUserRepo:      endUser,
		oauthAccountRepo: oAuthAccount,
		sessionRepo:      session,
	}
}

// NewRefreshToken initializes dependencies and constructs refreshToken.
func NewRefreshToken(infra *di.Infra) RefreshToken {
	session := repository.NewSession(infra.KVS)

	return &refreshToken{
		sessionRepo: session,
	}
}

// MustNewRefreshToken initializes dependencies and constructs refreshToken or panics on failure.
func MustNewRefreshToken(infra *di.Infra) RefreshToken {
	session := repository.NewSession(infra.KVS)

	return &refreshToken{
		sessionRepo: session,
	}
}
