// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_sign_in_use_case.go
//
// Generated by this command:
//
//	mockgen -source=oauth_sign_in_use_case.go -destination=./mock_usecase/mock_oauth_sign_in_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/oauth/usecase"
)

// MockOAuthSignIn is a mock of OAuthSignIn interface.
type MockOAuthSignIn struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthSignInMockRecorder
	isgomock struct{}
}

// MockOAuthSignInMockRecorder is the mock recorder for MockOAuthSignIn.
type MockOAuthSignInMockRecorder struct {
	mock *MockOAuthSignIn
}

// NewMockOAuthSignIn creates a new mock instance.
func NewMockOAuthSignIn(ctrl *gomock.Controller) *MockOAuthSignIn {
	mock := &MockOAuthSignIn{ctrl: ctrl}
	mock.recorder = &MockOAuthSignInMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthSignIn) EXPECT() *MockOAuthSignInMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockOAuthSignIn) Do(ctx context.Context, input usecase.OAuthSignInInput) (usecase.OAuthSignInOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.OAuthSignInOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockOAuthSignInMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOAuthSignIn)(nil).Do), ctx, input)
}
