// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_callback_use_case.go
//
// Generated by this command:
//
//	mockgen -source=oauth_callback_use_case.go -destination=./mock_usecase/mock_oauth_callback_use_case.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	usecase "mickamy.com/sampay/internal/domain/oauth/usecase"
)

// MockOAuthCallback is a mock of OAuthCallback interface.
type MockOAuthCallback struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthCallbackMockRecorder
	isgomock struct{}
}

// MockOAuthCallbackMockRecorder is the mock recorder for MockOAuthCallback.
type MockOAuthCallbackMockRecorder struct {
	mock *MockOAuthCallback
}

// NewMockOAuthCallback creates a new mock instance.
func NewMockOAuthCallback(ctrl *gomock.Controller) *MockOAuthCallback {
	mock := &MockOAuthCallback{ctrl: ctrl}
	mock.recorder = &MockOAuthCallbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthCallback) EXPECT() *MockOAuthCallbackMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockOAuthCallback) Do(ctx context.Context, input usecase.OAuthCallbackInput) (usecase.OAuthCallbackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(usecase.OAuthCallbackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockOAuthCallbackMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOAuthCallback)(nil).Do), ctx, input)
}
