// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/event/model"
)

// EventParticipants returns a new Query for the event_participants table.
func EventParticipants(db orm.Querier) *orm.Query[model.EventParticipant] {
	q := orm.NewQuery[model.EventParticipant](
		db, orm.ResolveTableName[model.EventParticipant]("event_participants"), eventParticipantsColumns, "id",
		scanEventParticipant, eventParticipantColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setEventParticipantCreatedAt,
		[]string{"updated_at"},
		setEventParticipantUpdatedAt,
	)
	return q
}

var eventParticipantsColumns = []string{"id", "event_id", "name", "tier", "status", "created_at", "updated_at"}

func scanEventParticipant(rows *sql.Rows) (model.EventParticipant, error) {
	cols, _ := rows.Columns()
	var v model.EventParticipant
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "event_id":
			dest[i] = &v.EventID
		case "name":
			dest[i] = &v.Name
		case "tier":
			dest[i] = &v.Tier
		case "status":
			dest[i] = &v.Status
		case "created_at":
			dest[i] = &v.CreatedAt
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func eventParticipantColumnValuePairs(v *model.EventParticipant, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "event_id", "name", "tier", "status", "created_at", "updated_at"},
			[]any{v.ID, v.EventID, v.Name, v.Tier, v.Status, v.CreatedAt, v.UpdatedAt}
	}
	return []string{"event_id", "name", "tier", "status", "created_at", "updated_at"},
		[]any{v.EventID, v.Name, v.Tier, v.Status, v.CreatedAt, v.UpdatedAt}
}

func setEventParticipantCreatedAt(v *model.EventParticipant, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
func setEventParticipantUpdatedAt(v *model.EventParticipant, now time.Time) {
	v.UpdatedAt = now
}
