// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/event/model"
)

// EventTiers returns a new Query for the event_tiers table.
func EventTiers(db orm.Querier) *orm.Query[model.EventTier] {
	q := orm.NewQuery[model.EventTier](
		db, orm.ResolveTableName[model.EventTier]("event_tiers"), eventTiersColumns, "id",
		scanEventTier, eventTierColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setEventTierCreatedAt,
		[]string{"updated_at"},
		setEventTierUpdatedAt,
	)
	return q
}

var eventTiersColumns = []string{"id", "event_id", "tier", "count", "amount", "created_at", "updated_at"}

func scanEventTier(rows *sql.Rows) (model.EventTier, error) {
	cols, _ := rows.Columns()
	var v model.EventTier
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "event_id":
			dest[i] = &v.EventID
		case "tier":
			dest[i] = &v.Tier
		case "count":
			dest[i] = &v.Count
		case "amount":
			dest[i] = &v.Amount
		case "created_at":
			dest[i] = &v.CreatedAt
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func eventTierColumnValuePairs(v *model.EventTier, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "event_id", "tier", "count", "amount", "created_at", "updated_at"},
			[]any{v.ID, v.EventID, v.Tier, v.Count, v.Amount, v.CreatedAt, v.UpdatedAt}
	}
	return []string{"event_id", "tier", "count", "amount", "created_at", "updated_at"},
		[]any{v.EventID, v.Tier, v.Count, v.Amount, v.CreatedAt, v.UpdatedAt}
}

func setEventTierCreatedAt(v *model.EventTier, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
func setEventTierUpdatedAt(v *model.EventTier, now time.Time) {
	v.UpdatedAt = now
}
