// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/storage/repository"
)

// NewGetUploadURL initializes dependencies and constructs getUploadURL.
func NewGetUploadURL(infra *di.Infra) GetUploadURL {
	s3Object := repository.NewS3Object(infra.DB)

	return &getUploadURL{
		s3:        infra.S3,
		writer:    infra.WriterDB,
		s3ObjRepo: s3Object,
	}
}

// MustNewGetUploadURL initializes dependencies and constructs getUploadURL or panics on failure.
func MustNewGetUploadURL(infra *di.Infra) GetUploadURL {
	s3Object := repository.NewS3Object(infra.DB)

	return &getUploadURL{
		s3:        infra.S3,
		writer:    infra.WriterDB,
		s3ObjRepo: s3Object,
	}
}
