// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/event/repository"
	repository2 "github.com/mickamy/sampay/internal/domain/user/repository"
)

// NewClaimPayment initializes dependencies and constructs claimPayment.
func NewClaimPayment(infra *di.Infra) ClaimPayment {
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &claimPayment{
		writer:          infra.WriterDB,
		participantRepo: eventParticipant,
	}
}

// MustNewClaimPayment initializes dependencies and constructs claimPayment or panics on failure.
func MustNewClaimPayment(infra *di.Infra) ClaimPayment {
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &claimPayment{
		writer:          infra.WriterDB,
		participantRepo: eventParticipant,
	}
}

// NewCreateEvent initializes dependencies and constructs createEvent.
func NewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)
	eventTier := repository.NewEventTier(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
		tierRepo:  eventTier,
	}
}

// MustNewCreateEvent initializes dependencies and constructs createEvent or panics on failure.
func MustNewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)
	eventTier := repository.NewEventTier(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
		tierRepo:  eventTier,
	}
}

// NewDeleteEvent initializes dependencies and constructs deleteEvent.
func NewDeleteEvent(infra *di.Infra) DeleteEvent {
	event := repository.NewEvent(infra.DB)

	return &deleteEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// MustNewDeleteEvent initializes dependencies and constructs deleteEvent or panics on failure.
func MustNewDeleteEvent(infra *di.Infra) DeleteEvent {
	event := repository.NewEvent(infra.DB)

	return &deleteEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// NewGetEvent initializes dependencies and constructs getEvent.
func NewGetEvent(infra *di.Infra) GetEvent {
	event := repository.NewEvent(infra.DB)
	endUser := repository2.NewEndUser(infra.DB)
	userPaymentMethod := repository2.NewUserPaymentMethod(infra.DB)

	return &getEvent{
		reader:            infra.ReaderDB,
		eventRepo:         event,
		endUserRepo:       endUser,
		paymentMethodRepo: userPaymentMethod,
	}
}

// MustNewGetEvent initializes dependencies and constructs getEvent or panics on failure.
func MustNewGetEvent(infra *di.Infra) GetEvent {
	event := repository.NewEvent(infra.DB)
	endUser := repository2.NewEndUser(infra.DB)
	userPaymentMethod := repository2.NewUserPaymentMethod(infra.DB)

	return &getEvent{
		reader:            infra.ReaderDB,
		eventRepo:         event,
		endUserRepo:       endUser,
		paymentMethodRepo: userPaymentMethod,
	}
}

// NewJoinEvent initializes dependencies and constructs joinEvent.
func NewJoinEvent(infra *di.Infra) JoinEvent {
	event := repository.NewEvent(infra.DB)
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &joinEvent{
		writer:          infra.WriterDB,
		eventRepo:       event,
		participantRepo: eventParticipant,
	}
}

// MustNewJoinEvent initializes dependencies and constructs joinEvent or panics on failure.
func MustNewJoinEvent(infra *di.Infra) JoinEvent {
	event := repository.NewEvent(infra.DB)
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &joinEvent{
		writer:          infra.WriterDB,
		eventRepo:       event,
		participantRepo: eventParticipant,
	}
}

// NewListEventParticipants initializes dependencies and constructs listEventParticipants.
func NewListEventParticipants(infra *di.Infra) ListEventParticipants {
	event := repository.NewEvent(infra.DB)

	return &listEventParticipants{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// MustNewListEventParticipants initializes dependencies and constructs listEventParticipants or panics on failure.
func MustNewListEventParticipants(infra *di.Infra) ListEventParticipants {
	event := repository.NewEvent(infra.DB)

	return &listEventParticipants{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// NewListMyEvents initializes dependencies and constructs listMyEvents.
func NewListMyEvents(infra *di.Infra) ListMyEvents {
	event := repository.NewEvent(infra.DB)

	return &listMyEvents{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// MustNewListMyEvents initializes dependencies and constructs listMyEvents or panics on failure.
func MustNewListMyEvents(infra *di.Infra) ListMyEvents {
	event := repository.NewEvent(infra.DB)

	return &listMyEvents{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// NewUpdateEvent initializes dependencies and constructs updateEvent.
func NewUpdateEvent(infra *di.Infra) UpdateEvent {
	event := repository.NewEvent(infra.DB)
	eventTier := repository.NewEventTier(infra.DB)
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &updateEvent{
		writer:          infra.WriterDB,
		eventRepo:       event,
		tierRepo:        eventTier,
		participantRepo: eventParticipant,
	}
}

// MustNewUpdateEvent initializes dependencies and constructs updateEvent or panics on failure.
func MustNewUpdateEvent(infra *di.Infra) UpdateEvent {
	event := repository.NewEvent(infra.DB)
	eventTier := repository.NewEventTier(infra.DB)
	eventParticipant := repository.NewEventParticipant(infra.DB)

	return &updateEvent{
		writer:          infra.WriterDB,
		eventRepo:       event,
		tierRepo:        eventTier,
		participantRepo: eventParticipant,
	}
}
