// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/event/repository"
)

// NewCreateEvent initializes dependencies and constructs createEvent.
func NewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// MustNewCreateEvent initializes dependencies and constructs createEvent or panics on failure.
func MustNewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}
