// Code generated by injector. DO NOT EDIT.

package usecase

import (
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/event/repository"
)

// NewCreateEvent initializes dependencies and constructs createEvent.
func NewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// MustNewCreateEvent initializes dependencies and constructs createEvent or panics on failure.
func MustNewCreateEvent(infra *di.Infra) CreateEvent {
	event := repository.NewEvent(infra.DB)

	return &createEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// NewListMyEvents initializes dependencies and constructs listMyEvents.
func NewListMyEvents(infra *di.Infra) ListMyEvents {
	event := repository.NewEvent(infra.DB)

	return &listMyEvents{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// MustNewListMyEvents initializes dependencies and constructs listMyEvents or panics on failure.
func MustNewListMyEvents(infra *di.Infra) ListMyEvents {
	event := repository.NewEvent(infra.DB)

	return &listMyEvents{
		reader:    infra.ReaderDB,
		eventRepo: event,
	}
}

// NewUpdateEvent initializes dependencies and constructs updateEvent.
func NewUpdateEvent(infra *di.Infra) UpdateEvent {
	event := repository.NewEvent(infra.DB)

	return &updateEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}

// MustNewUpdateEvent initializes dependencies and constructs updateEvent or panics on failure.
func MustNewUpdateEvent(infra *di.Infra) UpdateEvent {
	event := repository.NewEvent(infra.DB)

	return &updateEvent{
		writer:    infra.WriterDB,
		eventRepo: event,
	}
}
