// Code generated by go-typesafe-i18n; DO NOT EDIT.
package messages

import "github.com/mickamy/go-typesafe-i18n"

// AuthHandlerLogoutAccessTokenNotSet returns a Message for "auth.handler.logout.access_token_not_set".
// Template: アクセストークンが設定されていません。
func AuthHandlerLogoutAccessTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.logout.access_token_not_set"}
}

// AuthHandlerLogoutRefreshTokenNotSet returns a Message for "auth.handler.logout.refresh_token_not_set".
// Template: リフレッシュトークンが設定されていません。
func AuthHandlerLogoutRefreshTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.logout.refresh_token_not_set"}
}

// AuthHandlerRefreshTokenTokenNotSet returns a Message for "auth.handler.refresh_token.token_not_set".
// Template: リフレッシュトークンが設定されていません。
func AuthHandlerRefreshTokenTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.refresh_token.token_not_set"}
}

// AuthMapperErrorUnknownOauthProvider returns a Message for "auth.mapper.error.unknown_oauth_provider".
// Template: 不明な OAuth プロバイダーです。
func AuthMapperErrorUnknownOauthProvider() i18n.Message {
	return i18n.Message{ID: "auth.mapper.error.unknown_oauth_provider"}
}

// AuthUseCaseErrorLogoutTokenMismatch returns a Message for "auth.use_case.error.logout_token_mismatch".
// Template: ログアウトトークンが一致しません。
func AuthUseCaseErrorLogoutTokenMismatch() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.logout_token_mismatch"}
}

// AuthUseCaseErrorOauthCallbackFailed returns a Message for "auth.use_case.error.oauth_callback_failed".
// Template: OAuthコールバックに失敗しました。
func AuthUseCaseErrorOauthCallbackFailed() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.oauth_callback_failed"}
}

// AuthUseCaseErrorSessionNotFound returns a Message for "auth.use_case.error.session_not_found".
// Template: 無効なセッションです。
func AuthUseCaseErrorSessionNotFound() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.session_not_found"}
}

// AuthUseCaseErrorSessionNotSet returns a Message for "auth.use_case.error.session_not_set".
// Template: セッションがセットされていません。
func AuthUseCaseErrorSessionNotSet() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.session_not_set"}
}

// AuthUseCaseErrorTokenInvalid returns a Message for "auth.use_case.error.token_invalid".
// Template: 無効なトークンです。
func AuthUseCaseErrorTokenInvalid() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.token_invalid"}
}

// AuthUseCaseErrorUnsupportedOauthProvider returns a Message for "auth.use_case.error.unsupported_oauth_provider".
// Template: サポートされていない OAuth プロバイダーです。
func AuthUseCaseErrorUnsupportedOauthProvider() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.unsupported_oauth_provider"}
}

// CommonResponseErrorInternal returns a Message for "common.response.error.internal".
// Template: ただいまアクセスが集中しております。しばらくしてから再度お試しください。
func CommonResponseErrorInternal() i18n.Message {
	return i18n.Message{ID: "common.response.error.internal"}
}

// UserMapperErrorUnknownPaymentMethodType returns a Message for "user.mapper.error.unknown_payment_method_type".
// Template: 不明な決済手段です。
func UserMapperErrorUnknownPaymentMethodType() i18n.Message {
	return i18n.Message{ID: "user.mapper.error.unknown_payment_method_type"}
}

// UserModelSlugErrorAlreadyTaken returns a Message for "user.model.slug.error.already_taken".
// Template: このスラッグは既に使用されています。
func UserModelSlugErrorAlreadyTaken() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.already_taken"}
}

// UserModelSlugErrorInvalidChars returns a Message for "user.model.slug.error.invalid_chars".
// Template: スラッグには英小文字・数字・ハイフンのみ使用できます。
func UserModelSlugErrorInvalidChars() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.invalid_chars"}
}

// UserModelSlugErrorIsUuid returns a Message for "user.model.slug.error.is_uuid".
// Template: UUID 形式のスラッグは使用できません。
func UserModelSlugErrorIsUuid() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.is_uuid"}
}

// UserModelSlugErrorReserved returns a Message for "user.model.slug.error.reserved".
// Template: このスラッグは予約されています。
func UserModelSlugErrorReserved() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.reserved"}
}

// UserModelSlugErrorTooLong returns a Message for "user.model.slug.error.too_long".
// Template: スラッグは30文字以内で入力してください。
func UserModelSlugErrorTooLong() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.too_long"}
}

// UserModelSlugErrorTooShort returns a Message for "user.model.slug.error.too_short".
// Template: スラッグは3文字以上で入力してください。
func UserModelSlugErrorTooShort() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.too_short"}
}
