// Code generated by go-typesafe-i18n; DO NOT EDIT.
package messages

import "github.com/mickamy/go-typesafe-i18n"

// AuthHandlerLogoutAccessTokenNotSet returns a Message for "auth.handler.logout.access_token_not_set".
// Template: アクセストークンが設定されていません。
func AuthHandlerLogoutAccessTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.logout.access_token_not_set"}
}

// AuthHandlerLogoutRefreshTokenNotSet returns a Message for "auth.handler.logout.refresh_token_not_set".
// Template: リフレッシュトークンが設定されていません。
func AuthHandlerLogoutRefreshTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.logout.refresh_token_not_set"}
}

// AuthHandlerRefreshTokenTokenNotSet returns a Message for "auth.handler.refresh_token.token_not_set".
// Template: リフレッシュトークンが設定されていません。
func AuthHandlerRefreshTokenTokenNotSet() i18n.Message {
	return i18n.Message{ID: "auth.handler.refresh_token.token_not_set"}
}

// AuthMapperErrorUnknownOauthProvider returns a Message for "auth.mapper.error.unknown_oauth_provider".
// Template: 不明な OAuth プロバイダーです。
func AuthMapperErrorUnknownOauthProvider() i18n.Message {
	return i18n.Message{ID: "auth.mapper.error.unknown_oauth_provider"}
}

// AuthUseCaseErrorLogoutTokenMismatch returns a Message for "auth.use_case.error.logout_token_mismatch".
// Template: ログアウトトークンが一致しません。
func AuthUseCaseErrorLogoutTokenMismatch() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.logout_token_mismatch"}
}

// AuthUseCaseErrorOauthCallbackFailed returns a Message for "auth.use_case.error.oauth_callback_failed".
// Template: OAuthコールバックに失敗しました。
func AuthUseCaseErrorOauthCallbackFailed() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.oauth_callback_failed"}
}

// AuthUseCaseErrorSessionNotFound returns a Message for "auth.use_case.error.session_not_found".
// Template: 無効なセッションです。
func AuthUseCaseErrorSessionNotFound() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.session_not_found"}
}

// AuthUseCaseErrorSessionNotSet returns a Message for "auth.use_case.error.session_not_set".
// Template: セッションがセットされていません。
func AuthUseCaseErrorSessionNotSet() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.session_not_set"}
}

// AuthUseCaseErrorTokenInvalid returns a Message for "auth.use_case.error.token_invalid".
// Template: 無効なトークンです。
func AuthUseCaseErrorTokenInvalid() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.token_invalid"}
}

// AuthUseCaseErrorUnsupportedOauthProvider returns a Message for "auth.use_case.error.unsupported_oauth_provider".
// Template: サポートされていない OAuth プロバイダーです。
func AuthUseCaseErrorUnsupportedOauthProvider() i18n.Message {
	return i18n.Message{ID: "auth.use_case.error.unsupported_oauth_provider"}
}

// CommonResponseErrorInternal returns a Message for "common.response.error.internal".
// Template: ただいまアクセスが集中しております。しばらくしてから再度お試しください。
func CommonResponseErrorInternal() i18n.Message {
	return i18n.Message{ID: "common.response.error.internal"}
}

// EventUseCaseErrorAlreadyClaimed returns a Message for "event.use_case.error.already_claimed".
// Template: すでに支払い申告済みです。
func EventUseCaseErrorAlreadyClaimed() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.already_claimed"}
}

// EventUseCaseErrorArchived returns a Message for "event.use_case.error.archived".
// Template: このイベントはアーカイブ済みのため、新たな参加はできません。
func EventUseCaseErrorArchived() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.archived"}
}

// EventUseCaseErrorEventMismatch returns a Message for "event.use_case.error.event_mismatch".
// Template: 参加者が指定されたイベントに属していません。
func EventUseCaseErrorEventMismatch() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.event_mismatch"}
}

// EventUseCaseErrorForbidden returns a Message for "event.use_case.error.forbidden".
// Template: このイベントにアクセスする権限がありません。
func EventUseCaseErrorForbidden() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.forbidden"}
}

// EventUseCaseErrorHeldAtRequired returns a Message for "event.use_case.error.held_at_required".
// Template: 開催日時は必須です。
func EventUseCaseErrorHeldAtRequired() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.held_at_required"}
}

// EventUseCaseErrorInvalidTier returns a Message for "event.use_case.error.invalid_tier".
// Template: ティアが無効です。
func EventUseCaseErrorInvalidTier() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.invalid_tier"}
}

// EventUseCaseErrorInvalidTierConfig returns a Message for "event.use_case.error.invalid_tier_config".
// Template: ティア構成が無効です。
func EventUseCaseErrorInvalidTierConfig() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.invalid_tier_config"}
}

// EventUseCaseErrorInvalidTierUpdate returns a Message for "event.use_case.error.invalid_tier_update".
// Template: 既存の参加者が使用しているティアを削除することはできません。
func EventUseCaseErrorInvalidTierUpdate() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.invalid_tier_update"}
}

// EventUseCaseErrorLocked returns a Message for "event.use_case.error.locked".
// Template: 参加者が支払い申告済みのため、このイベントは編集できません。
func EventUseCaseErrorLocked() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.locked"}
}

// EventUseCaseErrorNameRequired returns a Message for "event.use_case.error.name_required".
// Template: 名前は必須です。
func EventUseCaseErrorNameRequired() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.name_required"}
}

// EventUseCaseErrorNotFound returns a Message for "event.use_case.error.not_found".
// Template: イベントが見つかりません。
func EventUseCaseErrorNotFound() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.not_found"}
}

// EventUseCaseErrorParticipantNotFound returns a Message for "event.use_case.error.participant_not_found".
// Template: 参加者が見つかりません。
func EventUseCaseErrorParticipantNotFound() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.participant_not_found"}
}

// EventUseCaseErrorTierCountInvalid returns a Message for "event.use_case.error.tier_count_invalid".
// Template: ティア段階数は1、3、5のいずれかで指定してください。
func EventUseCaseErrorTierCountInvalid() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.tier_count_invalid"}
}

// EventUseCaseErrorTiersRequired returns a Message for "event.use_case.error.tiers_required".
// Template: ティア構成は必須です。
func EventUseCaseErrorTiersRequired() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.tiers_required"}
}

// EventUseCaseErrorTitleRequired returns a Message for "event.use_case.error.title_required".
// Template: タイトルは必須です。
func EventUseCaseErrorTitleRequired() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.title_required"}
}

// EventUseCaseErrorTotalAmountPositive returns a Message for "event.use_case.error.total_amount_positive".
// Template: 合計金額は1以上で入力してください。
func EventUseCaseErrorTotalAmountPositive() i18n.Message {
	return i18n.Message{ID: "event.use_case.error.total_amount_positive"}
}

// UserMapperErrorUnknownPaymentMethodType returns a Message for "user.mapper.error.unknown_payment_method_type".
// Template: 不明な決済手段です。
func UserMapperErrorUnknownPaymentMethodType() i18n.Message {
	return i18n.Message{ID: "user.mapper.error.unknown_payment_method_type"}
}

// UserModelSlugErrorAlreadyTaken returns a Message for "user.model.slug.error.already_taken".
// Template: このスラッグは既に使用されています。
func UserModelSlugErrorAlreadyTaken() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.already_taken"}
}

// UserModelSlugErrorInvalidChars returns a Message for "user.model.slug.error.invalid_chars".
// Template: スラッグには英小文字・数字・ハイフンのみ使用できます。
func UserModelSlugErrorInvalidChars() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.invalid_chars"}
}

// UserModelSlugErrorIsUuid returns a Message for "user.model.slug.error.is_uuid".
// Template: UUID 形式のスラッグは使用できません。
func UserModelSlugErrorIsUuid() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.is_uuid"}
}

// UserModelSlugErrorReserved returns a Message for "user.model.slug.error.reserved".
// Template: このスラッグは予約されています。
func UserModelSlugErrorReserved() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.reserved"}
}

// UserModelSlugErrorTooLong returns a Message for "user.model.slug.error.too_long".
// Template: スラッグは30文字以内で入力してください。
func UserModelSlugErrorTooLong() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.too_long"}
}

// UserModelSlugErrorTooShort returns a Message for "user.model.slug.error.too_short".
// Template: スラッグは3文字以上で入力してください。
func UserModelSlugErrorTooShort() i18n.Message {
	return i18n.Message{ID: "user.model.slug.error.too_short"}
}
