// Code generated by injector. DO NOT EDIT.

package job

import (
	config "github.com/mickamy/sampay/config"
	di "github.com/mickamy/sampay/internal/di"
	repository "github.com/mickamy/sampay/internal/domain/auth/repository"
	line "github.com/mickamy/sampay/internal/domain/messaging/lib/line"
	repository2 "github.com/mickamy/sampay/internal/domain/messaging/repository"
)

// NewClaimNotification initializes dependencies and constructs ClaimNotification.
func NewClaimNotification(infra *di.Infra) *ClaimNotification {
	oAuthAccount := repository.NewOAuthAccount(infra.DB)
	lineFriendship := repository2.NewLineFriendship(infra.DB)
	lineMessaging := config.LineMessaging()
	pushClient := line.NewPushClient(lineMessaging)

	return &ClaimNotification{
		reader:             infra.ReaderDB,
		oauthAccountRepo:   oAuthAccount,
		lineFriendshipRepo: lineFriendship,
		pushClient:         pushClient,
	}
}

// MustNewClaimNotification initializes dependencies and constructs ClaimNotification or panics on failure.
func MustNewClaimNotification(infra *di.Infra) *ClaimNotification {
	oAuthAccount := repository.NewOAuthAccount(infra.DB)
	lineFriendship := repository2.NewLineFriendship(infra.DB)
	lineMessaging := config.LineMessaging()
	pushClient := line.NewPushClient(lineMessaging)

	return &ClaimNotification{
		reader:             infra.ReaderDB,
		oauthAccountRepo:   oAuthAccount,
		lineFriendshipRepo: lineFriendship,
		pushClient:         pushClient,
	}
}

// NewJobs initializes dependencies and constructs Jobs.
func NewJobs(infra *di.Infra) *Jobs {
	claimNotification := NewClaimNotification(infra)

	return &Jobs{
		ClaimNotification: claimNotification,
	}
}

// MustNewJobs initializes dependencies and constructs Jobs or panics on failure.
func MustNewJobs(infra *di.Infra) *Jobs {
	claimNotification := NewClaimNotification(infra)

	return &Jobs{
		ClaimNotification: claimNotification,
	}
}
