name: Deploy Application
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/deploy

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOMAIN: stg.sampay.link

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY_STG }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: Set ansible vault password
        run: |
          mkdir -p provisioning/secrets
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > ./provisioning/secrets/ansible_vault_pass 

      - name: Execute ansible playbook
        run: |
          cd ./provisioning
          ANSIBLE_HOST=${{ env.DOMAIN }} \
          ANSIBLE_USER=ec2-user \
          ANSIBLE_SSH_KEY=key.pem \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_ADMIN_PASSWORD_STG }} \
          ansible-playbook -i ./inventory/web.yaml playbook.yaml \
          --vault-password-file ./secrets/ansible_vault_pass \

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183691452:role/GitHubActionsRole-590183691452
          aws-region: ap-northeast-1

      - name: Checkout repository on EC2
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.DOMAIN }} << 'EOF'
            if [ ! -d "sampay" ]; then
              GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" git clone git@github.com:mickamy/sampay.git
            fi
            cd sampay
            git checkout -b adhoc/${{ github.sha }}-${{ github.event.repository.updated_at }} 
            git add .
            git stash
            git branch --merged | grep -v \* | xargs git branch -D
            git fetch origin --prune
            git checkout ${{ github.ref_name }}
          EOF

      - name: Deploy backend application
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.DOMAIN }} \
            "bash ~/sampay/backend/bin/deploy.sh"

      - name: Deploy frontend application
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.DOMAIN }} \
            "bash ~/sampay/frontend/bin/deploy.sh"

      - name: Delete adhoc branch
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.DOMAIN }} \
            "git branch -D adhoc/${{ github.sha }}"

      - name: Rollback
        if: ${{ failure() }}
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.DOMAIN }} << 'EOF'
            cd sampay
            git checkout -
            sudo systemctl restart sampay-api
            sudo systemctl restart sampay-worker
            sudo systemctl restart sampay-frontend
          EOF
