name: Deploy Application
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_REGION: ap-northeast-1
      DOMAIN: stg.sampay.link

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183691452:role/GitHubActionsRole-590183691452
          aws-region: ap-northeast-1

      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Allow IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.SECURITY_GROUP_ID_STG }} \
          --protocol tcp \
          --port ${{ secrets.SSH_PORT_STG }} \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY_STG }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: Set ansible vault password
        run: |
          mkdir -p provisioning/secrets
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > ./provisioning/secrets/ansible_vault_pass

      - name: Execute ansible playbook
        run: |
          cd ./provisioning

          export ANSIBLE_SSH_KEY="${GITHUB_WORKSPACE}/key.pem"
          export ANSIBLE_SSH_PORT=${{ secrets.SSH_PORT_STG }}
          export AWS_REGION=${{ env.AWS_REGION }}
          export CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_ADMIN_PASSWORD_STG }}
          export KVS_PASSWORD=${{ secrets.KVS_PASSWORD_STG }}
          export BASIC_USER=${{ secrets.BASIC_USER }}
          export BASIC_PASSWORD=${{ secrets.BASIC_PASSWORD }}

          ansible-playbook -i ./inventory/web.yaml playbook.yaml \
          --vault-password-file ./secrets/ansible_vault_pass --limit stg \

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod
          cache-dependency-path: ./backend/go.sum

      - name: Set directory suffix
        run: |
          echo "DIR_SUFFIX=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build backend binaries
        run: cd backend && make build

      - name: Ensure app directory exists
        run: |
          ssh -p ${{ secrets.SSH_PORT_STG }} -i key.pem ec2-user@${{ env.DOMAIN }} -o StrictHostKeyChecking=no '
            mkdir -p /home/ec2-user/sampay
          '

      - name: Copy binaries to EC2 (build & db)
        run: |
          scp -r -i key.pem -P ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no \
            ./backend/build ./backend/db ec2-user@${{ env.DOMAIN }}:/home/ec2-user/sampay/backend-${{ env.DIR_SUFFIX }}/

      - name: Deploy backend application
        run: |
          cat "${GITHUB_WORKSPACE}/backend/bin/deploy.sh" |
          ssh -p ${{ secrets.SSH_PORT_STG }} -i key.pem ec2-user@${{ env.DOMAIN }} -o StrictHostKeyChecking=no '
            export DIR_SUFFIX="${{ env.DIR_SUFFIX }}";
            export NGINX_CONF="/etc/nginx/conf.d/stg.sampay.link.conf";
            bash -s
          '

      - name: Copy frontend files to EC2
        run: |
          scp -C -r -i key.pem -P ${{ secrets.SSH_PORT_STG }} -o StrictHostKeyChecking=no \
            ./frontend ec2-user@${{ env.DOMAIN }}:/home/ec2-user/sampay/frontend-${{ env.DIR_SUFFIX }}

      - name: Deploy frontend application
        run: |
          cat "${GITHUB_WORKSPACE}/frontend/bin/deploy.sh" |
          ssh -p ${{ secrets.SSH_PORT_STG }} -i key.pem ec2-user@${{ env.DOMAIN }} -o StrictHostKeyChecking=no '
            export DIR_SUFFIX="${{ env.DIR_SUFFIX }}";
            export NGINX_CONF="/etc/nginx/conf.d/stg.sampay.link.conf";
            bash -s
          '

      - name: Revoke IP from Security Group
        if: ${{ always() }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID_STG }} \
            --protocol tcp \
            --port ${{ secrets.SSH_PORT_STG }} \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
