name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  backend:
    services:
      postgres:
        image: postgres:16.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
          TZ: Asia/Tokyo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7.0.15-alpine
        env:
          REDIS_PASSWORD: password
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a password ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod
          cache-dependency-path: ./backend/go.sum

      - uses: bufbuild/buf-setup-action@v1

      - name: Install dependencies
        run: cd backend && make install

      - name: Verify all files are up to date
        run: |
          cd backend && make gen

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after generation."
            git diff
            exit 1
          fi

      - name: Verify all files are formatted
        run: |
          cd backend && make fmt

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after generation."
            git diff
            exit 1
          fi

      - name: Lint
        run: cd backend && make lint

      - name: Inject .env
        run: |
          cd backend && cat <<EOF > .env
            TZ=Asia/Tokyo
            ENV=development
            PACKAGE_ROOT=$(pwd)
          
            DB_HOST=localhost
            DB_PORT=5432
            DB_WRITER_USER=sampay_writer
            DB_WRITER_PASSWORD=password
            DB_READER_USER=sampay_reader
            DB_READER_PASSWORD=password
            DB_NAME=sampay
            DB_TIMEZONE=Asia/Tokyo
            DB_ADMIN_USER=postgres
            DB_ADMIN_PASSWORD=password
          
            DATABASE_WRITER_URL=postgresql://$DB_WRITER_USER:$DB_WRITER_USER@$DB_HOST:$DB_PORT/$DB_NAME?timezone=$DB_TIMEZONE&sslmode=disable
            DATABASE_READER_URL=postgresql://$DB_READER_USER:$DB_READER_USER@$DB_HOST:$DB_PORT/$DB_NAME?timezone=$DB_TIMEZONE&sslmode=disable
          
            # for golang-migrate/migrate
            POSTGRESQL_URL=$DATABASE_WRITER_URL
          
            REDIS_URL=redis://:password@localhost:6379/0
          
            JWT_SIGNING_SECRET=secret
          
            AWS_REGION=ap-northeast-1
            AWS_ACCESS_KEY_ID=test
            AWS_ACCESS_KEY_SECRET=test
            CLOUDFRONT_DOMAIN=localhost
            LOCALSTACK_ENDPOINT=http://localhost:4566
            S3_PUBLIC_BUCKET_NAME=sampay-public
          EOF

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: '4.0.3'
          install-awslocal: 'true'

      - name: Execute localstack init script
        run: ./localstack/init.sh

      - name: Prepare Database
        run: cd backend && make db-prepare

      - name: Test
        run: cd backend && make test

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Type check
        run: cd frontend && npm run typecheck

      - name: Verify all files are formatted
        run: |
          cd frontend && npm run check

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after generation."
            git diff
            exit 1
          fi
