// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"
	"time"

	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/sampay/internal/domain/storage/model"
)

// S3Objects returns a new Query for the s3_objects table.
func S3Objects(db orm.Querier) *orm.Query[model.S3Object] {
	q := orm.NewQuery[model.S3Object](
		db, orm.ResolveTableName[model.S3Object]("s3_objects"), s3ObjectsColumns, "id",
		scanS3Object, s3ObjectColumnValuePairs, nil,
	)
	q.RegisterTimestamps(
		[]string{"created_at"},
		setS3ObjectCreatedAt,
		[]string{"updated_at"},
		setS3ObjectUpdatedAt,
	)
	return q
}

var s3ObjectsColumns = []string{"id", "bucket", "key", "created_at", "updated_at"}

func scanS3Object(rows *sql.Rows) (model.S3Object, error) {
	cols, _ := rows.Columns()
	var v model.S3Object
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "bucket":
			dest[i] = &v.Bucket
		case "key":
			dest[i] = &v.Key
		case "created_at":
			dest[i] = &v.CreatedAt
		case "updated_at":
			dest[i] = &v.UpdatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func s3ObjectColumnValuePairs(v *model.S3Object, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "bucket", "key", "created_at", "updated_at"},
			[]any{v.ID, v.Bucket, v.Key, v.CreatedAt, v.UpdatedAt}
	}
	return []string{"bucket", "key", "created_at", "updated_at"},
		[]any{v.Bucket, v.Key, v.CreatedAt, v.UpdatedAt}
}

func setS3ObjectCreatedAt(v *model.S3Object, now time.Time) {
	if v.CreatedAt.IsZero() {
		v.CreatedAt = now
	}
}
func setS3ObjectUpdatedAt(v *model.S3Object, now time.Time) {
	v.UpdatedAt = now
}
